import "server-only";
import {and, asc, desc, eq, isNotNull, isNull} from "drizzle-orm";
import {z} from "zod";
import {requireAdmin} from "@/lib/auth/authorize";
import {getDb} from "@/lib/db/repos/common";
import {auditEvents, landingPartners, type LandingPartner} from "@/lib/db/server-schema";
import type {Actor, AdminActor} from "@/lib/membership/lifecycle";

const idSchema = z.string().uuid();
const text = (max: number) => z.string().transform((value) => value.trim()).refine((value) => Array.from(value).length >= 1 && Array.from(value).length <= max, "LANDING_PARTNER_TEXT_INVALID");
const inputObject = z.object({organizationEn: text(160), organizationZhHk: text(160), market: text(120), region: text(120), mouStatus: z.enum(["prospect", "in_discussion", "signed", "inactive"]), contact: z.record(z.unknown()).default({}), notes: z.union([z.string().trim().max(5000), z.null()]).optional().transform((value) => value || null)}).strict();
const inputSchema = inputObject; const updateSchema = inputObject.partial().refine((value) => Object.keys(value).length > 0, "LANDING_PARTNER_UPDATE_EMPTY");
type Input = z.output<typeof inputSchema>; type Patch = z.output<typeof updateSchema>;
type Audit = Readonly<{actorUserId: string; actorType: AdminActor["kind"]; action: `landing_partner.${"created" | "updated" | "published" | "unpublished" | "archived" | "unarchived"}`; targetType: "landing_partner"; targetId: string; metadata: Record<string, unknown>}>;
export type LandingPartnerMutationDependencies = Readonly<{transaction: <T>(work: (tx: Readonly<{insertPartner: (input: Input) => Promise<LandingPartner>; lockPartner: (id: string) => Promise<LandingPartner | null>; updatePartner: (id: string, input: Patch) => Promise<LandingPartner | null>; setPublishedAt: (id: string, value: Date | null) => Promise<LandingPartner | null>; setArchivedAt: (id: string, value: Date | null) => Promise<LandingPartner | null>; insertAudit: (input: Audit) => Promise<void>}>) => Promise<T>) => Promise<T>}>;
export type LandingPartnerReadDependencies = Readonly<{list: (limit: number) => Promise<readonly LandingPartner[]>; get: (id: string) => Promise<LandingPartner | null>}>;
export type LandingPartnerProjection = Readonly<Pick<LandingPartner, "id" | "organizationEn" | "organizationZhHk" | "market" | "region">>;
export type LandingPartnerPublicSource = readonly LandingPartner[] | Readonly<{list: (limit: number) => Promise<readonly LandingPartner[]>}>;
async function mutations(): Promise<LandingPartnerMutationDependencies> { const db = await getDb(); return {transaction: (work) => db.transaction(async (tx) => work({insertPartner: async (input) => { const [row] = await tx.insert(landingPartners).values(input).returning(); if (!row) throw new Error("LANDING_PARTNER_INSERT_FAILED"); return row; }, lockPartner: async (id) => (await tx.select().from(landingPartners).where(eq(landingPartners.id, id)).for("update"))[0] ?? null, updatePartner: async (id, input) => (await tx.update(landingPartners).set({...input, updatedAt: new Date()}).where(eq(landingPartners.id, id)).returning())[0] ?? null, setPublishedAt: async (id, value) => (await tx.update(landingPartners).set({publishedAt: value, updatedAt: new Date()}).where(eq(landingPartners.id, id)).returning())[0] ?? null, setArchivedAt: async (id, value) => (await tx.update(landingPartners).set({archivedAt: value, updatedAt: new Date()}).where(eq(landingPartners.id, id)).returning())[0] ?? null, insertAudit: async (input) => { await tx.insert(auditEvents).values(input); }}))}; }
async function reads(): Promise<LandingPartnerReadDependencies> { const db = await getDb(); return {list: (limit) => db.select().from(landingPartners).orderBy(desc(landingPartners.createdAt), asc(landingPartners.id)).limit(limit), get: async (id) => (await db.select().from(landingPartners).where(eq(landingPartners.id, id)).limit(1))[0] ?? null}; }
async function publicSource(): Promise<Exclude<LandingPartnerPublicSource, readonly LandingPartner[]>> { const db = await getDb(); return {list: (limit) => db.select().from(landingPartners).where(and(eq(landingPartners.mouStatus, "signed"), isNotNull(landingPartners.publishedAt), isNull(landingPartners.archivedAt))).orderBy(asc(landingPartners.market), asc(landingPartners.organizationEn), asc(landingPartners.id)).limit(limit)}; }
function audit(actor: AdminActor, action: Audit["action"], row: LandingPartner, metadata: Record<string, unknown> = {}): Audit { return {actorUserId: actor.profileId, actorType: actor.kind, action, targetType: "landing_partner", targetId: row.id, metadata}; }
function hasPublicReader(source: LandingPartnerPublicSource): source is Exclude<LandingPartnerPublicSource, readonly LandingPartner[]> { return !Array.isArray(source); }
export async function createLandingPartner(actor: Actor, input: unknown, dependencies?: LandingPartnerMutationDependencies) { requireAdmin(actor); const parsed = inputSchema.parse(input); return (dependencies ?? await mutations()).transaction(async (tx) => { const row = await tx.insertPartner(parsed); await tx.insertAudit(audit(actor, "landing_partner.created", row, {market: row.market})); return row; }); }
export async function updateLandingPartner(actor: Actor, id: unknown, input: unknown, dependencies?: LandingPartnerMutationDependencies) { requireAdmin(actor); const parsedId = idSchema.parse(id); const parsed = updateSchema.parse(input); return (dependencies ?? await mutations()).transaction(async (tx) => { const current = await tx.lockPartner(parsedId); if (!current) return null; if (current.publishedAt && parsed.mouStatus !== undefined && parsed.mouStatus !== "signed") throw new Error("LANDING_PARTNER_LIFECYCLE_INVALID"); const row = await tx.updatePartner(parsedId, parsed); if (!row) return null; await tx.insertAudit(audit(actor, "landing_partner.updated", row, {fields: Object.keys(parsed).sort()})); return row; }); }
export async function setLandingPartnerPublished(actor: Actor, id: unknown, published: boolean, dependencies?: LandingPartnerMutationDependencies, clock: () => Date = () => new Date()) { requireAdmin(actor); const parsedId = idSchema.parse(id); return (dependencies ?? await mutations()).transaction(async (tx) => { const current = await tx.lockPartner(parsedId); if (!current) return null; if (published && current.archivedAt) throw new Error("LANDING_PARTNER_LIFECYCLE_INVALID"); if (published === Boolean(current.publishedAt)) return current; if (published && current.mouStatus !== "signed") throw new Error("LANDING_PARTNER_PUBLICATION_NOT_READY"); const row = await tx.setPublishedAt(parsedId, published ? clock() : null); if (!row) return null; await tx.insertAudit(audit(actor, published ? "landing_partner.published" : "landing_partner.unpublished", row)); return row; }); }
export async function setLandingPartnerArchived(actor: Actor, id: unknown, archived: boolean, dependencies?: LandingPartnerMutationDependencies, clock: () => Date = () => new Date()) { requireAdmin(actor); const parsedId = idSchema.parse(id); return (dependencies ?? await mutations()).transaction(async (tx) => { const current = await tx.lockPartner(parsedId); if (!current) return null; if (archived && current.publishedAt) throw new Error("LANDING_PARTNER_LIFECYCLE_INVALID"); if (archived === Boolean(current.archivedAt)) return current; const row = await tx.setArchivedAt(parsedId, archived ? clock() : null); if (!row) return null; await tx.insertAudit(audit(actor, archived ? "landing_partner.archived" : "landing_partner.unarchived", row)); return row; }); }
export async function listLandingPartnersForAdmin(actor: Actor, dependencies?: LandingPartnerReadDependencies) { requireAdmin(actor); return (dependencies ?? await reads()).list(100); }
export async function getLandingPartnerForAdmin(actor: Actor, id: unknown, dependencies?: LandingPartnerReadDependencies) { requireAdmin(actor); const parsed = idSchema.safeParse(id); return parsed.success ? (dependencies ?? await reads()).get(parsed.data) : null; }
export async function listPublishedLandingPartners(options: Readonly<{limit?: number}> = {}, source?: LandingPartnerPublicSource): Promise<readonly LandingPartnerProjection[]> { const limit = z.number().int().min(1).max(100).parse(options.limit ?? 100); const selected = source ?? await publicSource(); const rows: readonly LandingPartner[] = hasPublicReader(selected) ? await selected.list(limit) : selected.filter((row) => row.mouStatus === "signed" && row.publishedAt && !row.archivedAt).sort((a, b) => a.market.localeCompare(b.market) || a.organizationEn.localeCompare(b.organizationEn) || a.id.localeCompare(b.id)).slice(0, limit); return rows.map(({id, organizationEn, organizationZhHk, market, region}) => ({id, organizationEn, organizationZhHk, market, region})); }
export const landingPartnersRepository = {create: createLandingPartner, update: updateLandingPartner, setPublished: setLandingPartnerPublished, setArchived: setLandingPartnerArchived, listForAdmin: listLandingPartnersForAdmin, getForAdmin: getLandingPartnerForAdmin, listPublished: listPublishedLandingPartners};
