import "server-only";

import {and, asc, desc, eq, getTableColumns, gte, isNotNull, isNull, lte, or, sql} from "drizzle-orm";
import {z} from "zod";
import {requireAdmin} from "@/lib/auth/authorize";
import {getDb} from "@/lib/db/repos/common";
import {auditEvents, media, partners, type MediaRow, type Partner} from "@/lib/db/server-schema";
import {canonicalHttpsUrl} from "@/lib/security/https-url";
import type {Actor, AdminActor} from "@/lib/membership/lifecycle";

const idSchema = z.string().uuid();
const localeSchema = z.enum(["en", "zh-HK"]);
const jsTrimCharacters = "\u0009\u000a\u000b\u000c\u000d\u0020\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000\ufeff";
const dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine((value) => { const date = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value; }, "PARTNER_DATE_INVALID");
const text = (maximum: number) => z.string().transform((value) => value.trim()).refine((value) => Array.from(value).length >= 1 && Array.from(value).length <= maximum, "PARTNER_TEXT_INVALID");
const optionalWebsite = z.union([z.literal(""), z.null(), z.undefined()]).transform(() => null).or(z.string().transform((value, context) => { try { return canonicalHttpsUrl(value); } catch { context.addIssue({code: z.ZodIssueCode.custom, message: "HTTPS_URL_INVALID"}); return z.NEVER; } }));
const optionalId = z.union([z.literal(""), z.null(), z.undefined()]).transform(() => null).or(idSchema);
const optionalDate = z.union([z.literal(""), z.null(), z.undefined()]).transform(() => null).or(dateSchema);
const partnerObject = z.object({nameEn: text(160), nameZhHk: text(160), category: z.enum(["supporting", "media", "regional", "programme", "sponsor"]), websiteUrl: optionalWebsite, logoMediaId: optionalId, displayOrder: z.number().int().min(0).max(10000), featured: z.boolean(), relationshipStartsOn: optionalDate, relationshipEndsOn: optionalDate, relationshipConfirmed: z.boolean().optional(), logoRightsConfirmed: z.boolean().optional()}).strict();
const partnerInputSchema = partnerObject.superRefine((value, context) => { if (value.relationshipStartsOn && value.relationshipEndsOn && value.relationshipEndsOn < value.relationshipStartsOn) context.addIssue({code: z.ZodIssueCode.custom, path: ["relationshipEndsOn"], message: "PARTNER_RELATIONSHIP_WINDOW_INVALID"}); });
const partnerUpdateSchema = partnerObject.partial().refine((value) => Object.keys(value).length > 0, "PARTNER_UPDATE_EMPTY");

type PartnerInput = z.output<typeof partnerInputSchema>;
type PartnerWrite = Omit<PartnerInput, "relationshipConfirmed" | "logoRightsConfirmed"> & {relationshipConfirmedAt: Date | null; logoRightsConfirmedAt: Date | null};
type PartnerPatch = Partial<PartnerWrite>;
type Audit = Readonly<{actorUserId: string; actorType: AdminActor["kind"]; action: `partner.${"created" | "updated" | "published" | "unpublished" | "archived" | "unarchived"}`; targetType: "partner"; targetId: string; metadata: Record<string, unknown>}>;
type LockedMedia = Pick<MediaRow, "id" | "url" | "altEn" | "altZh" | "archivedAt">;

export type PartnerMutationDependencies = Readonly<{transaction: <T>(work: (tx: Readonly<{insertPartner: (input: PartnerWrite) => Promise<Partner>; getPartner: (id: string) => Promise<Partner | null>; lockMedia: (id: string) => Promise<LockedMedia | null>; lockPartner: (id: string) => Promise<Partner | null>; updatePartner: (id: string, input: PartnerPatch) => Promise<Partner | null>; setPublishedAt: (id: string, value: Date | null) => Promise<Partner | null>; setArchivedAt: (id: string, value: Date | null) => Promise<Partner | null>; insertAudit: (input: Audit) => Promise<void>}>) => Promise<T>) => Promise<T>}>;
export type PartnerReadDependencies = Readonly<{list: (limit: number) => Promise<readonly Partner[]>; get: (id: string) => Promise<Partner | null>}>;
export type PublicPartnerRow = Partner & Readonly<{logoMediaUrl?: string | null; logoMediaAltEn?: string | null; logoMediaAltZh?: string | null; logoMediaArchivedAt?: Date | null}>;
export type PartnerProjection = Readonly<{id: string; name: string; category: Partner["category"]; websiteUrl: string | null; logoUrl: string | null | undefined; logoAlt: string | null | undefined; displayOrder: number; featured: boolean}>;
type PartnerLocale = z.output<typeof localeSchema>;
export type PartnerPublicSource = readonly PublicPartnerRow[] | Readonly<{list: (today: string, now: Date, locale: PartnerLocale, limit: number) => Promise<readonly PublicPartnerRow[]>}>;

function publicationError(): never { throw new Error("PARTNER_PUBLICATION_NOT_READY"); }
function validMedia(row: LockedMedia | null, requireAlt: boolean): asserts row is LockedMedia { if (!row || row.archivedAt || (requireAlt && (!row.altEn.trim() || !row.altZh.trim()))) publicationError(); }
function hkDate(clock: Date): string { const parts = new Intl.DateTimeFormat("en-CA", {timeZone: "Asia/Hong_Kong", year: "numeric", month: "2-digit", day: "2-digit"}).formatToParts(clock); const value = Object.fromEntries(parts.map((part) => [part.type, part.value])); return `${value.year}-${value.month}-${value.day}`; }
function toWrite(parsed: PartnerInput, clock: Date): PartnerWrite { const {relationshipConfirmed, logoRightsConfirmed, ...fields} = parsed; return {...fields, relationshipConfirmedAt: relationshipConfirmed ? clock : null, logoRightsConfirmedAt: logoRightsConfirmed ? clock : null}; }

async function mutations(): Promise<PartnerMutationDependencies> { const db = await getDb(); return {transaction: (work) => db.transaction(async (tx) => work({insertPartner: async (input) => { const [row] = await tx.insert(partners).values(input).returning(); if (!row) throw new Error("PARTNER_INSERT_FAILED"); return row; }, getPartner: async (id) => (await tx.select().from(partners).where(eq(partners.id, id)).limit(1))[0] ?? null, lockMedia: async (id) => (await tx.select({id: media.id, url: media.url, altEn: media.altEn, altZh: media.altZh, archivedAt: media.archivedAt}).from(media).where(eq(media.id, id)).for("update"))[0] ?? null, lockPartner: async (id) => (await tx.select().from(partners).where(eq(partners.id, id)).for("update"))[0] ?? null, updatePartner: async (id, input) => (await tx.update(partners).set({...input, updatedAt: new Date()}).where(eq(partners.id, id)).returning())[0] ?? null, setPublishedAt: async (id, value) => (await tx.update(partners).set({publishedAt: value, updatedAt: new Date()}).where(eq(partners.id, id)).returning())[0] ?? null, setArchivedAt: async (id, value) => (await tx.update(partners).set({archivedAt: value, updatedAt: new Date()}).where(eq(partners.id, id)).returning())[0] ?? null, insertAudit: async (input) => { await tx.insert(auditEvents).values(input); }}))}; }
async function reads(): Promise<PartnerReadDependencies> { const db = await getDb(); return {list: (limit) => db.select().from(partners).orderBy(desc(partners.createdAt), asc(partners.id)).limit(limit), get: async (id) => (await db.select().from(partners).where(eq(partners.id, id)).limit(1))[0] ?? null}; }
async function publicSource(): Promise<Exclude<PartnerPublicSource, readonly PublicPartnerRow[]>> { const db = await getDb(); return {list: (today, now, locale, limit) => db.select({...getTableColumns(partners), logoMediaUrl: media.url, logoMediaAltEn: media.altEn, logoMediaAltZh: media.altZh, logoMediaArchivedAt: media.archivedAt}).from(partners).innerJoin(media, eq(partners.logoMediaId, media.id)).where(and(isNull(partners.archivedAt), isNotNull(partners.publishedAt), lte(partners.publishedAt, now), isNotNull(partners.relationshipConfirmedAt), isNotNull(partners.logoRightsConfirmedAt), isNull(media.archivedAt), sql`char_length(btrim(${media.altEn}, ${jsTrimCharacters})) > 0`, sql`char_length(btrim(${media.altZh}, ${jsTrimCharacters})) > 0`, or(isNull(partners.relationshipStartsOn), lte(partners.relationshipStartsOn, today)), or(isNull(partners.relationshipEndsOn), gte(partners.relationshipEndsOn, today)))).orderBy(desc(partners.featured), asc(partners.displayOrder), asc(locale === "zh-HK" ? partners.nameZhHk : partners.nameEn), asc(partners.id)).limit(limit)}; }
function audit(actor: AdminActor, action: Audit["action"], row: Partner, metadata: Record<string, unknown> = {}): Audit { return {actorUserId: actor.profileId, actorType: actor.kind, action, targetType: "partner", targetId: row.id, metadata}; }
function hasPublicReader(source: PartnerPublicSource): source is Exclude<PartnerPublicSource, readonly PublicPartnerRow[]> { return !Array.isArray(source); }

export async function createPartner(actor: Actor, input: unknown, dependencies?: PartnerMutationDependencies, clock: () => Date = () => new Date()): Promise<Partner> { requireAdmin(actor); const parsed = partnerInputSchema.parse(input); const now = clock(); return (dependencies ?? await mutations()).transaction(async (tx) => { if (parsed.logoMediaId) validMedia(await tx.lockMedia(parsed.logoMediaId), false); const row = await tx.insertPartner(toWrite(parsed, now)); await tx.insertAudit(audit(actor, "partner.created", row, {category: row.category})); return row; }); }
export async function updatePartner(actor: Actor, id: unknown, input: unknown, dependencies?: PartnerMutationDependencies, clock: () => Date = () => new Date()): Promise<Partner | null> { requireAdmin(actor); const parsedId = idSchema.parse(id); const parsed = partnerUpdateSchema.parse(input); const now = clock(); return (dependencies ?? await mutations()).transaction(async (tx) => { const observed = await tx.getPartner(parsedId); if (!observed) return null; const logoId = parsed.logoMediaId === undefined ? observed.logoMediaId : parsed.logoMediaId; const lockedMedia = logoId ? await tx.lockMedia(logoId) : null; if (logoId) validMedia(lockedMedia, false); const current = await tx.lockPartner(parsedId); if (!current) return null; const effectiveLogoId = parsed.logoMediaId === undefined ? current.logoMediaId : parsed.logoMediaId; if (effectiveLogoId !== logoId || (effectiveLogoId && lockedMedia?.id !== effectiveLogoId)) throw new Error("PARTNER_LOGO_CHANGED_RETRY"); const patch: PartnerPatch = {...parsed}; delete (patch as Record<string, unknown>).relationshipConfirmed; delete (patch as Record<string, unknown>).logoRightsConfirmed; if (parsed.relationshipConfirmed !== undefined) patch.relationshipConfirmedAt = parsed.relationshipConfirmed ? now : null; if (parsed.logoRightsConfirmed !== undefined) patch.logoRightsConfirmedAt = parsed.logoRightsConfirmed ? now : null; const start = patch.relationshipStartsOn === undefined ? current.relationshipStartsOn : patch.relationshipStartsOn; const end = patch.relationshipEndsOn === undefined ? current.relationshipEndsOn : patch.relationshipEndsOn; if (start && end && end < start) throw new Error("PARTNER_RELATIONSHIP_WINDOW_INVALID"); if (current.publishedAt) { const effective = {...current, ...patch}; if (!effective.relationshipConfirmedAt || !effective.logoRightsConfirmedAt || !effective.logoMediaId) publicationError(); validMedia(lockedMedia, true); } const row = await tx.updatePartner(parsedId, patch); if (!row) return null; await tx.insertAudit(audit(actor, "partner.updated", row, {fields: Object.keys(patch).sort()})); return row; }); }
export async function setPartnerPublished(actor: Actor, id: unknown, published: boolean, dependencies?: PartnerMutationDependencies, clock: () => Date = () => new Date()): Promise<Partner | null> { requireAdmin(actor); const parsedId = idSchema.parse(id); return (dependencies ?? await mutations()).transaction(async (tx) => { const observed = await tx.getPartner(parsedId); if (!observed) return null; const logo = observed.logoMediaId ? await tx.lockMedia(observed.logoMediaId) : null; const current = await tx.lockPartner(parsedId); if (!current) return null; if (current.logoMediaId !== observed.logoMediaId || (current.logoMediaId && logo?.id !== current.logoMediaId)) throw new Error("PARTNER_LOGO_CHANGED_RETRY"); if (published && current.archivedAt) throw new Error("PARTNER_LIFECYCLE_INVALID"); if (published === Boolean(current.publishedAt)) return current; if (published) { if (!current.relationshipConfirmedAt || !current.logoRightsConfirmedAt || !current.logoMediaId) publicationError(); validMedia(logo, true); } const row = await tx.setPublishedAt(parsedId, published ? clock() : null); if (!row) return null; await tx.insertAudit(audit(actor, published ? "partner.published" : "partner.unpublished", row)); return row; }); }
export async function setPartnerArchived(actor: Actor, id: unknown, archived: boolean, dependencies?: PartnerMutationDependencies, clock: () => Date = () => new Date()): Promise<Partner | null> { requireAdmin(actor); const parsedId = idSchema.parse(id); return (dependencies ?? await mutations()).transaction(async (tx) => { const observed = await tx.getPartner(parsedId); if (!observed) return null; const logo = observed.logoMediaId ? await tx.lockMedia(observed.logoMediaId) : null; const current = await tx.lockPartner(parsedId); if (!current) return null; if (current.logoMediaId !== observed.logoMediaId || (current.logoMediaId && logo?.id !== current.logoMediaId)) throw new Error("PARTNER_LOGO_CHANGED_RETRY"); if (archived && current.publishedAt) throw new Error("PARTNER_LIFECYCLE_INVALID"); if (archived === Boolean(current.archivedAt)) return current; const row = await tx.setArchivedAt(parsedId, archived ? clock() : null); if (!row) return null; await tx.insertAudit(audit(actor, archived ? "partner.archived" : "partner.unarchived", row)); return row; }); }
export async function listPartnersForAdmin(actor: Actor, dependencies?: PartnerReadDependencies) { requireAdmin(actor); return (dependencies ?? await reads()).list(100); }
export async function getPartnerForAdmin(actor: Actor, id: unknown, dependencies?: PartnerReadDependencies) { requireAdmin(actor); const parsed = idSchema.safeParse(id); return parsed.success ? (dependencies ?? await reads()).get(parsed.data) : null; }
export async function listPublishedPartners(localeInput: unknown, options: Readonly<{limit?: number; asOf?: Date}> = {}, source?: PartnerPublicSource): Promise<readonly PartnerProjection[]> { const locale = localeSchema.parse(localeInput); const limit = z.number().int().min(1).max(100).parse(options.limit ?? 50); const now = z.date().parse(options.asOf ?? new Date()); const today = hkDate(now); const selected = source ?? await publicSource(); const rows: readonly PublicPartnerRow[] = hasPublicReader(selected) ? await selected.list(today, now, locale, limit) : selected.filter((row) => !row.archivedAt && row.publishedAt && row.publishedAt <= now && row.relationshipConfirmedAt && row.logoRightsConfirmedAt && row.logoMediaId && !row.logoMediaArchivedAt && Boolean(row.logoMediaAltEn?.trim()) && Boolean(row.logoMediaAltZh?.trim()) && (!row.relationshipStartsOn || row.relationshipStartsOn <= today) && (!row.relationshipEndsOn || row.relationshipEndsOn >= today)).sort((a, b) => Number(b.featured) - Number(a.featured) || a.displayOrder - b.displayOrder || (locale === "zh-HK" ? a.nameZhHk : a.nameEn).localeCompare(locale === "zh-HK" ? b.nameZhHk : b.nameEn) || a.id.localeCompare(b.id)).slice(0, limit); return rows.map((row) => ({id: row.id, name: locale === "zh-HK" ? row.nameZhHk : row.nameEn, category: row.category, websiteUrl: row.websiteUrl, logoUrl: row.logoMediaUrl, logoAlt: locale === "zh-HK" ? row.logoMediaAltZh : row.logoMediaAltEn, displayOrder: row.displayOrder, featured: row.featured})); }

export const partnersRepository = {create: createPartner, update: updatePartner, setPublished: setPartnerPublished, setArchived: setPartnerArchived, listForAdmin: listPartnersForAdmin, getForAdmin: getPartnerForAdmin, listPublished: listPublishedPartners};
