import {milestoneSchema, type MilestoneRecord} from '@/content/schemas';

// Reviewed from content/milestones.draft.json against the captured
// hkwtia.org archive: each entry's kind was checked against its title and
// body, the 12 percent-encoded WordPress slugs were replaced with real
// ASCII slugs, non-milestone kinds were forced un-featured, and image srcs
// were rewritten to ASCII-safe filenames (see content/milestone-image-map.json
// for the original-to-new mapping Task 6 needs to download correctly).
// titleZh/bodyZh are intentionally empty -- Task 7 drafts the missing locale.
export const milestones: MilestoneRecord[] = milestoneSchema.array().parse([
  {
    slug: '2001-establishment-of-wtia',
    kind: 'milestone',
    year: 2001,
    month: '01',
    titleEn: '2001 - Establishment of WTIA',
    titleZh: '',
    bodyEn: 'The Inauguration Ceremony of WTIA was held at Hong Kong Productivity Council, with the exhibition Wireless Application Showcase. 20 companies showcased their latest mobile and wireless application in the Showcase.',
    bodyZh: '',
    images: [
      {src: '/images/history/2001-The-Inauguration-of-WTIA-1024x683-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2001/01/2001-establishment-of-wtia/',
    featured: false,
  },
  {
    slug: '2002-the-1st-wtia-panel-discussion-inter-operator-sms',
    kind: 'milestone',
    year: 2002,
    month: '01',
    titleEn: '2002 - The 1st WTIA Panel Discussion: Inter-Operator SMS',
    titleZh: '',
    bodyEn: 'Representatives of mobile network operators discussed the feasibility of transmitting SMS between different operators in the panel discussion of Wireless Technology Forum organized by WTIA in 2002.',
    bodyZh: '',
    images: [],
    legacyPath: '/2002/01/2002-the-1st-wtia-panel-discussion-inter-operator-sms/',
    featured: false,
  },
  {
    slug: '2003-opening-of-hong-kong-wireless-development-centre-at-cyberport',
    kind: 'milestone',
    year: 2003,
    month: '01',
    titleEn: '2003 - Opening of Hong Kong Wireless Development Centre at Cyberport',
    titleZh: '',
    bodyEn: 'With support of HKSAR Government, Cyberport and more than 30 corporations, WTIA established the Hong Kong Wireless Development Centre (WDC) to showcase Hong Kong’s latest development and advancement in mobile technology . Feature of the Centre included testing hubs and technical consultancy for mobile application developers, and also demonstration of mobile applications and wireless products that are established in Hong Kong. TD-SCDMA Application Development Centre also set up in WDC and served as the only testing hub for TD-SCDMA network outside Greater China Region.',
    bodyZh: '',
    images: [
      {src: '/images/history/WDC-OPening03-1024x686-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2003/01/2003-opening-of-hong-kong-wireless-development-centre-at-cyberport/',
    featured: false,
  },
  {
    slug: '2003-the-1st-wtia-awards-j2me-open-2003',
    kind: 'milestone',
    year: 2003,
    month: '01',
    titleEn: '2003 - The 1st WTIA Awards: J2ME Open 2003',
    titleZh: '',
    bodyEn: 'Aimed to encourage development of wireless applications for consumers and enterprises, the contest J2ME Open 2003 was organized by WTIA. Over 300 teams participated the contest.',
    bodyZh: '',
    images: [],
    legacyPath: '/2003/01/2003-the-1st-wtia-awards-j2me-open-2003/',
    featured: false,
  },
  {
    slug: '2003-wtia-partner-with-pisa-to-conduct-wlan-war-driving-in-hong-kong',
    kind: 'milestone',
    year: 2003,
    month: '01',
    titleEn: '2003 - WTIA Partner with PISA to Conduct WLAN War Driving in Hong Kong',
    titleZh: '',
    bodyEn: 'WTIA collaborated with Professional Information Security Association (PISA) to conduct War Driving survey for evaluating the strength of security measures performed by WLAN users in Hong Kong, and raise public awareness of the importance of WLAN security. The project later re-branded as SafeWiFi, and the War Driving transformed as a testing on the security level of Wi-Fi hotspot in Hong Kong.',
    bodyZh: '',
    images: [
      {src: '/images/history/wlan-wardriving-1024x620-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2003/01/2003-wtia-partner-with-pisa-to-conduct-wlan-war-driving-in-hong-kong/',
    featured: false,
  },
  {
    slug: '2005-1st-hong-kong-wireless-technology-excellence-awards',
    kind: 'milestone',
    year: 2005,
    month: '01',
    titleEn: '2005 - 1st Hong Kong Wireless Technology Excellence Awards',
    titleZh: '',
    bodyEn: 'WTIA and Hong Kong Productivity Council (HKPC) organized the 1st Hong Kong Wireless Technology Excellence Awards to recognize the best mobile and wireless applications developed by local companies.',
    bodyZh: '',
    images: [
      {src: '/images/history/1st-hk-excellence-1024x625-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2005/01/2005-1st-hong-kong-wireless-technology-excellence-awards/',
    featured: false,
  },
  {
    slug: '2005-hong-kong-international-wireless-conference-2005',
    kind: 'milestone',
    year: 2005,
    month: '01',
    titleEn: '2005 - Hong Kong International Wireless Conference 2005',
    titleZh: '',
    bodyEn: 'Thousands of visitors from globe participated this international event organized by WTIA. The event consisted of presentation by reputable speakers and exhibition of 20 local wireless technology applications and solutions providers.',
    bodyZh: '',
    images: [
      {src: '/images/history/Seminar-2005-1024x712-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2005/01/2005-hong-kong-international-wireless-conference-2005/',
    featured: false,
  },
  {
    slug: '2005-launching-of-3g-cyberport-project',
    kind: 'milestone',
    year: 2005,
    month: '01',
    titleEn: '2005 - Launching of 3G Cyberport Project',
    titleZh: '',
    bodyEn: 'Supported by Office of the Government Chief Information Officer (OGCIO), Cyberport and local 3G network operators, WTIA launched the 3G Cyberport Project. The Project consisted of awards, training, forum, and exhibition to promote the development and adoption of 3G applications and solutions in Hong Kong.',
    bodyZh: '',
    images: [],
    legacyPath: '/2005/01/2005-launching-of-3g-cyberport-project/',
    featured: false,
  },
  {
    slug: '2005-launching-of-wireless-services-value-chain-cooperation-wsvcc-platform',
    kind: 'milestone',
    year: 2005,
    month: '01',
    titleEn: '2005 - Launching of Wireless Services Value Chain Cooperation (WSVCC) platform',
    titleZh: '',
    bodyEn: 'WTIA established the Wireless Services Value Chain Cooperation (WSVCC) platform in the Pearl River Delta of Mainland China in 2005. Content localization services equipped with hardware and technical support were provided in the platform to simplify the process of launching mobile applications in China.',
    bodyZh: '',
    images: [
      {src: '/images/history/GZ-Centre-1024x768-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2005/01/2005-launching-of-wireless-services-value-chain-cooperation-wsvcc-platform/',
    featured: false,
  },
  {
    slug: '2005-the-1st-wtia-sms-donation-campaign',
    kind: 'milestone',
    year: 2005,
    month: '01',
    titleEn: '2005 - The 1st WTIA SMS Donation Campaign',
    titleZh: '',
    bodyEn: 'WTIA and Internet Professionals Association (iProA) partnered with mobile network operators in Hong Kong to launch an SMS Donation Campaign, and raised HK $2 million for the victims of 2004 Indian Ocean earthquake and tsunami.',
    bodyZh: '',
    images: [],
    legacyPath: '/2005/01/2005-the-1st-wtia-sms-donation-campaign/',
    featured: false,
  },
  {
    slug: '2006-hong-kong-ict-awards-best-ubiquitous-award',
    kind: 'milestone',
    year: 2006,
    month: '01',
    titleEn: '2006 - Hong Kong ICT Awards: Best Ubiquitous Award',
    titleZh: '',
    bodyEn: 'Steered by the Office of the Government Chief Information Officer (OGCIO) and organized by WTIA, Hong Kong ICT Awards: Best Ubiquitous Award established in 2006 to promote Hong Kong’s identity in providing quality mobile and wireless technology and application, and also honour the best local development in the field. The Award renamed as Hong Kong ICT Awards: Best Mobile Apps Award in 2013.',
    bodyZh: '',
    images: [
      {src: '/images/history/ICTAwards01.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2006/01/2006-hong-kong-ict-awards-best-ubiquitous-award/',
    featured: false,
  },
  {
    slug: '2007-hong-kong-mobile-film-festival',
    kind: 'milestone',
    year: 2007,
    month: '01',
    titleEn: '2007 - Hong Kong Mobile Film Festival',
    titleZh: '',
    bodyEn: 'WTIA organized the first Hong Kong Mobile Film Festival in 2007. With activities including production contest, seminar and workshops, the festival aims to nurture local youngsters’ interest and knowledge in mobile film productions and promote the awareness of mobile films appreciation among the general public.',
    bodyZh: '',
    images: [
      {src: '/images/history/2nd-HKMFF-Launching01-1024x683-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2007/01/2007-hong-kong-mobile-film-festival/',
    featured: false,
  },
  {
    slug: '2013-asia-smartphone-contest',
    kind: 'milestone',
    year: 2013,
    month: '01',
    titleEn: '2013 - Asia Smartphone Contest',
    titleZh: '',
    bodyEn: 'To recognize the excellence of innovative smartphone applications development and provide a platform for top smartphone applications professionals in the region to meet, share, collaborate and learn from each other, WTIA started to organize Asia Smartphone Contest in 2013. 7 Asia Regions, including Israel, Mainland China, Japan, Korea, Malaysia, Singapore, Taiwan was the co-organizer of the Contest.',
    bodyZh: '',
    images: [
      {src: '/images/history/1978490_525772187522812_9029582140716785616_o-1024x683-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2013/01/2013-asia-smartphone-contest/',
    featured: false,
  },
  {
    slug: '2013-opening-of-mobility-experience-centre-at-cyberport',
    kind: 'milestone',
    year: 2013,
    month: '01',
    titleEn: '2013 - Opening of Mobility Experience Centre at Cyberport',
    titleZh: '',
    bodyEn: 'With the support of Cyberport, WDC is renovated as Mobility Experience Centre (MEC) in 2013. The establishment of MEC aims to provide a space for public to experience advanced mobile devices, and also highlights the illustrious accomplishments Hong Kong has achieved in mobile technology. Outstanding and award-winning applications and wireless technology-related products developed by local IT companies are showcasing in the Centre.',
    bodyZh: '',
    images: [
      {src: '/images/history/902576_358199000946799_1828693650_o-1024x684-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2013/01/2013-opening-of-mobility-experience-centre-at-cyberport/',
    featured: false,
  },
  {
    slug: '2014-made-in-hong-kong-smartphone-apps-project',
    kind: 'milestone',
    year: 2014,
    month: '01',
    titleEn: '2014 - Made in Hong Kong Smartphone Apps Project',
    titleZh: '',
    bodyEn: 'In order to assist the local application developers to expand their business in Mainland China market, “Made in Hong Kong” Smartphone Apps Project was organized by WTIA to initiate a series of events. “Made in Hong Kong” Smartphone Apps Gallery is a platform that is specifically designed to promote applications that are developed by local developers to users in Mainland China. Over 500 applications are featured in the Gallery. Moreover, Seminar, workshops and visit to China were also held to facilitate business networking opportunities between local mobile app companies and potential clients in China.',
    bodyZh: '',
    images: [
      {src: '/images/history/10669026_572211736212190_588421535425640444_o-1024x683-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2014/01/2014-made-in-hong-kong-smartphone-apps-project/',
    featured: false,
  },
  {
    slug: '2014-wi-fi-hk',
    kind: 'milestone',
    year: 2014,
    month: '01',
    titleEn: '2014 - Wi-Fi.HK',
    titleZh: '',
    bodyEn: 'WTIA and Office of the Government Chief Information Officer (OGCIO) launched Wi-Fi.HK, a common Wi-Fi brand established to facilitate the public and visitors in locating and accessing the free public Wi-Fi services in Hong Kong. With the support from both public and private sectors, there are over 12,000 hotspots under the brand to provide easy access of free Wi-Fi services to the public and visitors.',
    bodyZh: '',
    images: [
      {src: '/images/history/10548114_546835835416447_7807130283769467394_o-1024x683-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2014/01/2014-wi-fi-hk/',
    featured: false,
  },
  {
    slug: '2015-asia-smartphone-apps-contest-summit-2015',
    kind: 'milestone',
    year: 2015,
    month: '01',
    titleEn: '2015 – Asia Smartphone Apps Contest & Summit 2015',
    titleZh: '',
    bodyEn: 'To recognize the excellence of innovative smartphone applications development and provide a platform for top smartphone applications professions in the region to meet, share and learn from each other, WTIA started to organise Asia Smartphone Contest in 2013, 7 Asia Regions, including Israel, Mainland China, Japan, Korea, Malaysia, Singapore, Taiwan was the co-organiser of the Contest.',
    bodyZh: '',
    images: [
      {src: '/images/history/ASA-2014.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2015/01/2015-asia-smartphone-apps-contest-summit-2015/',
    featured: false,
  },
  {
    slug: '2015-hong-kong-ict-awards-2015-best-mobile-apps-award',
    kind: 'milestone',
    year: 2015,
    month: '01',
    titleEn: '2015 – Hong Kong ICT Awards 2015: Best Mobile Apps Award',
    titleZh: '',
    bodyEn: 'Supported by Office of the Government Chief Information Officer (OGCIO) and organized by WTIA, The Best Mobile Apps Awards aims to honour the best local mobile and wireless technology and application development, also to encourage further mobile and wireless technology and application development with enhanced creativity, design and commercial value.',
    bodyZh: '',
    images: [
      {src: '/images/history/2015-ICT-Awards.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2015/01/2015-hong-kong-ict-awards-2015-best-mobile-apps-award/',
    featured: false,
  },
  {
    slug: '2015-safewifi-campaign',
    kind: 'milestone',
    year: 2015,
    month: '01',
    titleEn: '2015 – SafeWiFi Campaign',
    titleZh: '',
    bodyEn: 'In order to raise public awareness in Wi-Fi security, WTIA started SafeWiFi.hk and set up the thematic website in 2001. SafeWiFi Campaign aim at investigating the WiFi usage, assessibility, security and the knowledge of it in Hong Kong, which conducted annual WiFi security survey and co-organize events to promote Wi-Fi security for the public.',
    bodyZh: '',
    images: [
      {src: '/images/history/2015-SafeWiFi.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2015/01/2015-safewifi-campaign/',
    featured: false,
  },
  {
    slug: '2015-the-5th-hong-kong-international-mobile-film-festival-and-awards',
    kind: 'milestone',
    year: 2015,
    month: '01',
    titleEn: '2015 - The 5th Hong Kong International Mobile Film Festival and Awards',
    titleZh: '',
    bodyEn: 'The Project hosted since 2007, with the funding support from Create Hong Kong of HKSAR Government. With activities including production contest, seminar and workshops, the festival aims to contribute to the industry development through (1) Introducing local talents and their quality mobile videos to the international platforms to encourage mobile contents developments; (2) Broadening the horizons of local talents by facilitating the experience and culture exchanges among excellent filmmakers around the world; (3) Enhancing public awareness of using mobile devices for daily enjoyment',
    bodyZh: '',
    images: [
      {src: '/images/history/2014HKMFF.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2015/01/2015-the-5th-hong-kong-international-mobile-film-festival-and-awards/',
    featured: false,
  },
  {
    slug: '2016-asia-smartphone-apps-summit-cum-award-presentation-ceremony-2016',
    kind: 'milestone',
    year: 2016,
    month: '01',
    titleEn: '2016 - Asia Smartphone Apps Summit cum Award Presentation Ceremony 2016',
    titleZh: '',
    bodyEn: 'To recognize the excellence of innovative smartphone applications development and provide a platform for top smartphone applications professions in the region to meet, share and learn from each other, WTIA started to organise Asia Smartphone Contest in 2013, 9 Asia Regions, including Israel, Mainland China, Japan, Korea, Malaysia, Singapore, Taiwan was the co-organiser of the Contest.',
    bodyZh: '',
    images: [
      {src: '/images/history/Picture1-1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2016/01/2016-asia-smartphone-apps-summit-cum-award-presentation-ceremony-2016/',
    featured: false,
  },
  {
    slug: '2016-building-up-wi-fi-hk-through-collaboration-pledging-ceremony',
    kind: 'milestone',
    year: 2016,
    month: '01',
    titleEn: '2016 – “Building up Wi-Fi.HK through Collaboration” Pledging Ceremony”',
    titleZh: '',
    bodyEn: 'The Office of the Government Chief Information Officer together with the Hong Kong Wireless Technology Industry Association (WTIA) held the "Building Up Wi-Fi.HK Through Collaboration" Pledging Ceremony on 30 March 2016. The event called for the active participation of public and private organisations in promoting free public Wi-Fi service with the Government through the Wi-Fi.HK scheme to facilitate easy access to the Internet by the public.',
    bodyZh: '',
    images: [
      {src: '/images/history/2016-Wi-Fi.HK_.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2016/01/2016-building-up-wi-fi-hk-through-collaboration-pledging-ceremony/',
    featured: false,
  },
  {
    slug: '2016-legco-information-technology-constituency-election-forum',
    kind: 'milestone',
    year: 2016,
    month: '01',
    titleEn: '2016 - LegCo Information Technology Constituency Election Forum',
    titleZh: '',
    bodyEn: 'To create a platform for IT voters to understand more about the candidates’ view for the upcoming LEGCO Election IT Functional Constituency, Hong Kong Wireless Technology Industry Association (WTIA), the Hong Kong Information Technology Federation (HKITF), and Professional Information Security Association (PISA) co-organized an Election Forum in 2016 before the legislative election.',
    bodyZh: '',
    images: [
      {src: '/images/history/Picture1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2016/01/2016-legco-information-technology-constituency-election-forum/',
    featured: false,
  },
  {
    slug: '2016-safewifi-campaign',
    kind: 'milestone',
    year: 2016,
    month: '01',
    titleEn: '2016 – SafeWiFi Campaign',
    titleZh: '',
    bodyEn: 'In order to raise public awareness in Wi-Fi security, WTIA started SafeWiFi.hk and set up the thematic website in 2001. SafeWiFi Campaign aim at investigating the WiFi usage, assessibility, security and the knowledge of it in Hong Kong, which conducted annual WiFi security survey and co-organize events to promote Wi-Fi security for the public.',
    bodyZh: '',
    images: [
      {src: '/images/history/2016-SafeWiFi.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2016/01/2016-safewifi-campaign/',
    featured: false,
  },
  {
    slug: 'wtia-meet-our-member-cypher-martin',
    kind: 'member-story',
    year: 2016,
    month: '08',
    titleEn: 'WTIA Meet Our Member – 馬田電腦 (Cypher Martin)',
    titleZh: '',
    bodyEn: '專訪：市場及項目總經理Daniel Hui (Cypher Martin Systems Ltd. 馬田電腦系統有限公司) http://www.cypher-it.com/\n\n甫踏進Cypher Martin的辦公室，即見到植物上「青蘋果紅蘋果」。Daniel說近年公司的目標是「遍地綠一抹紅」，除了視覺上顏色跟公司標誌很接近之外，亦有意將發展計劃形象化，令同事們更容易明白了解公司目標。\n\n自2001年轉型以來，Cypher Martin除了提供網路硬件外，更是無線網絡、網絡安全及通信系統解決方案的表表者，提供一站式到位服務。而無線網絡架設殊不簡單，每每先由專業網路工程師配以偵測儀器作實地考察，再擬訂網路架設方案及購置合適設備等，全由系統工程師們包辦。游走於各式各樣的解決方案與顧及不同客戶的多方面考慮，總不能每個方案都花上最多的資源，所以定下遍地綠一抹紅這方展方向，為客戶度身訂造「紅蘋果」；以基本技術支援和定立標準套餐的「綠蘋果」，兩者間取得平衡使公司與市場及受惠者都能豐收！\n\n遍地綠一點紅 – 用心栽種，守候結果\n\n種出遍地果林，絕非靠一個人一雙手便能成事，背後要有團隊的支持。Daniel在尋找好”農夫”時也下了不少心思。除了跟各大院校合作吸納新血外，Cypher Martin亦非常著重同事的個人成長。工程師們不單有技術根基，其他事物也需要認識。因為工作環境周邊有不同元素直接或間接影響整個成長和觀察分析的角度；由如何與客戶溝通，表達自己時不要過急或直腸直肚，以至挑選顯示個人專業的衣著，Daniel和他的團隊都頗有心得及樂於與同事分享。\n\n在Cypher Martin入口附近有一個圖書角，內有工具書、管理書、人物傳記、甚至小說散文，亦準備一些飲品小食供同事自由借閱及享用，鼓勵同事多方面及展，不只單純在「手作技術」上有增長，也讓同事在享受精神食糧時帶來一些comfort food為自己「叉叉電」，擴闊生活，甚至是想法、視野。\n\n此外，讓同事又愛又恨的就是每月例會中的「三分鐘」演講，每次同事會有不同主題或自訂題目進行輕鬆交流。例如工程師會為其他同事解說最新的技術方案或旅遊的見聞，非技術同事可能會為大家分享一下時事或對技術的看法和見解，加深同事間互相了解之餘，不論是工作的範疇或者個人的生活體驗，也能為較少機會作公開演說的團隊壯大膽量，加強溝通技巧，相得益彰。\n\n其中令Daniel最難忘的是：同事結婚致辭時，特別感謝Cypher Martin這三分鐘訓練，令本身內向的自己能夠向在場嘉賓流暢地演說，更助他娶到好老婆。Daniel說：「你付出的可能沒有即時收穫，但你永遠不知道這些些微的滋養會為身邊的人帶來怎樣的變化。正如網絡鋪設一樣，眼看是簡單幾條電線和一些會閃光的器材，但接通後為該場所帶來的回饋可超乎所想。」\n\nCisco是Cypher Martin的長期合作伙伴，連毛公仔也打呔上班',
    bodyZh: '',
    images: [
      {src: '/images/history/Cypher-Martin-Office-scaled.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Cypher-Martin-Daniel-2-768x758-1.jpg', altEn: '', altZh: ''},
      {src: '/images/history/cypher-apple-2-768x789-1.jpg', altEn: '', altZh: ''},
      {src: '/images/history/cypher-bear-768x1024-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2016/08/wtia-meet-our-member-%e9%a6%ac%e7%94%b0%e9%9b%bb%e8%85%a6-cypher-martin/',
    featured: false,
  },
  {
    slug: 'wtia-meet-our-member-vpon-big-data-group',
    kind: 'member-story',
    year: 2016,
    month: '09',
    titleEn: 'WTIA Meet Our Member – 威朋大數據集團 (Vpon Big Data Group)',
    titleZh: '',
    bodyEn: '專訪：香港區總經理陳明發 (Vpon Big Data Group 威朋大數據集團)\n\nhttp://www.vpon.com/\n\n「Vpon是一間Big Data公司，而不只是手機流動廣告公司。」訪問開始，香港區總經理陳明發(Arthur)劈頭第一句說。\n\nVpon 2008年於台灣成立，當時做的是手機優惠券(Mobile Coupon)。由於手機優惠券業務範圍狹窄，公司於2011年正式開始轉型，同年於上海成立台灣以外的辦公室，研發當時尚未普及、但門檻更高的手機流動廣告。2014年正式打進香港市場，成為台北、上海及東京後第四個據點。\n\n執筆之時，消息指蘋果將要發布可能名為iPhone7的新一代智能手機。當iPhone已經發展至第七代，大家也可以預計到手機及數碼營銷的市場成熟而且競爭劇烈，那Vpon有什麼過人之處?\n\n「數碼營銷，特別是手機流動營銷，並不是你從前在蘋果日報落廣告，到PC年代在蘋果日報網頁落廣告，現在則到蘋果日報App落廣告。每人使用手機、網頁、App等都有不同使用習慣，傳統Media Buy的廣告購買型式已經不太合適。」\n\nVpon是本港少數運用大數據分析，為客戶提供針對性及度身訂造式的營銷方案的公司。大數據分析的好處，正好切合手機流動市場碎片化及快速轉變的環境生態，針對個別手機用家不同的喜好及需求，甚至基於各種情景去接觸目標受眾，提升營銷活動效益。\n\n「其中一種做法是利用情景模式，例如汽車品牌想吸引人到九龍灣的陳列室，將廣告在適當的時間放在身處陳列室附近的目標對象。另外，透過人工智能將海量的Big Data構造成超過六百個的群組視角作分析，然後找出目標受眾，精準度當然比傳統Media Buy等只用到二至三個範疇的數據來得高。當然兩者亦可以結合締造最理想的效果。」\n\nVpon其中一個引以為傲的項目，便是針對跨境旅客的宣傳方案。利用手機及位置等資訊，追蹤旅客的位置並於過境後發放個人化的手機流動廣告，將旅客直接從邊境牽引至商戶消費，提高宣傳效益之餘，亦可讓客戶了解及分析目標顧客的選擇。\n\nVpon辦公室有家居舒適感覺，白色簡潔色有助同事思考，橙色Corporate Color形成對比、啟發創意，讓邏輯創意兼備的同事左右腦交叉運用。\n\n近年資訊科技及數碼營銷市場都興起大數據(Big Data)一詞，Vpon有提供使用Big Data分析的方案，究竟Big Data可怎樣協助客戶呢？\n\n「市場上很多人誤解Big Data及Data Mining(資料探勘)，兩者的概念是完全不同的。」\n\n當然，兩者是不可以比較的。Data Mining是一種方法，Big Data則是龐大數據集的統稱。\n\nData Mining是從眾多資料中提取有用資訊，並搜尋隱藏於不同資料中的特殊關聯性，從而發掘出過去未知的有價值資訊。這方法與數據量無關，可以在一般數據庫(甚至是Excel試算表)上進行，也可以在Big Data的龐大數據集上進行。\n\n當數據量未能作出準確分析及提供足夠有用資訊，便需要利用「Big Data」增加數據作進一步分析。Big Data的數據量，規模巨大及複雜得無法透過人工或者普通電腦進行分析。這種龐大的數據規模需要運用到先進的電腦設備配合演算法(Algorithm)，才可在合理的時間內擷取、分析並整理(也就是Data Mining)成為人類所能解讀的形式的資訊。\n\n「所以，不要迷信Big Data。」Arthur相當坦白。「適當時候用大數據，但有些情況用簡單的數據分析已可以解決大部分市場的客戶需求，Vpon強調的是合理性，不是過分吹噓Big Data天下無敵。」\n\n當然，Vpon在Big Data的應用上有其個人之處。他們在台灣及上海的辦公室有一半員工是技術員及數據分析師，設計不同演算法達致客戶所需。例如，他們為Uber在內地宣傳，由於各省市的乘客習慣有所不同，所以便需要利用Big Data及演算法分析各省市龐大數據，制定在地而即時的宣傳策略，提高宣傳效率。\n\n既然台灣及上海一半技術人員，香港又如何呢？Arthur坦言香港的辦公室專注業務銷售層面，不過，他的聘請方向也反映了Vpon不只是一間傳統的廣告公司。\n\n「我聘請的同事碰巧都未必有廣告背景，這可能與數碼營銷的行業特性有關。數碼營銷要先講求邏輯推理，再配合創意才可達理想效果。」\n\n以「邏輯優先」的請人方針，正好體現了文章開首所說，「Vpon是一間Big Data公司」。',
    bodyZh: '',
    images: [
      {src: '/images/history/Vpon-Arthur-Chan-scaled.jpg', altEn: '', altZh: ''},
      {src: '/images/history/office-3-768x512-1.jpg', altEn: '', altZh: ''},
      {src: '/images/history/HK_team_1-768x512-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2016/09/wtia-meet-our-member-%e5%a8%81%e6%9c%8b%e5%a4%a7%e6%95%b8%e6%93%9a%e9%9b%86%e5%9c%98-vpon-big-data-group/',
    featured: false,
  },
  {
    slug: 'wtia-meet-our-member-rohde-schwarz-hong-kong-ltd',
    kind: 'member-story',
    year: 2016,
    month: '12',
    titleEn: 'WTIA Meet Our Member – 羅德與施瓦茨香港有限公司 Rohde & Schwarz (Hong Kong) Ltd.',
    titleZh: '',
    bodyEn: '專訪：董事總經理 Frank Wong 王鴻 (Rohde & Schwarz Hong Kong Limited 羅德與施瓦茨香港有限公司)\n\nhttps://www.rohde-schwarz.com/hk/\n\nRohde & Schwarz Hong Kong Limited辦公室位於香港科學園無線電中心，單看其所在位置便能感覺與我們香港無線科技商有某種聯繫。\n\n「Rohde & Schwarz，很多人誤以為是賣藥的。」董事總經理Frank如是說。的而且確，Rohde & Schwarz這名字和某R字頭的藥廠有點相似。\n\nRohde和Schwarz其實是兩位創辦人的名字，公司1933年於德國創立，成立至今一直以來都以無線科技為主要業務，總部設在德國慕尼黑，業務分佈於全球超過70國家及地區，是全球最大的電子和無線流動通訊測試設備廠商之一。而香港的分公司則於2006年成立，Frank現在主要負責港、澳、台地區的業務。\n\n圖: Rohde & Schwarz Hong Kong Limited 董事總經理 Frank Wong\n\nRohde & Schwarz主要有五大業務範疇：\n\n從以上幾點可看到Rohde & Schwarz的業務廣闊，我們試試從一些實際的例子了解他們的工作。香港業務方面，一些例子包括「香港電台電視31」慈雲山發射站內的發射機、有自己研發的LTE-Advanced檢測儀、香港生產力促進局有購買他們的頻譜分析儀、香港海事處亦有使用他們的船隻航行監察服務系統等等。其他產品包括電影後製壓縮打包系統，《阿凡達》、《哈比人》及Netflix某些節目亦有使用Rohde和Schwarz的產品進行製作。德國總公司則剛推出了新型的機場安檢儀器，開拓不同市場。\n\nFrank憶述，Rohde & Schwarz的起飛是在2G至3G及3G至4G兩個年代。在2G剛起步的年代，流動通訊在不同國家地區有不同標準。作為一家德國公司，Rohde & Schwarz理所當然地配合歐洲的標準，以歐洲國家制定的GSM制式作研發基礎，為手機廠製作GSM System Simulator作產品檢測，成為當時為數不多提供GSM檢測儀器的公司。隨著時代發展，GSM於芸芸制式中成為全球廣泛通用的標準，此機遇為公司帶來極大盈利，讓Rohde & Schwarz迎來第一個起飛點。同時，2G年代的經驗亦讓他們有更好準備，為日後3G及4G發展打好基礎。\n\n20多年過去，現今4G已經發展成熟，不少人甚至已經在提及5G的發展及可能性，Rohde和Schwarz在無線流動通訊測試設備有豐富經驗，他們又怎樣迎接5G年代的來臨呢？Frank認為5G是全新的技術，公司當然會著手準備5G的發展，在海外及國內亦簽訂一些合作計劃。但5G現在仍在發展測試及討論階段，相信要商業化仍有一段長時間。始終現階段4G網絡用量仍未飽和，中間應會經歷4.5G的年代，才有需要在大眾層面上應用到5G技術。\n\n在物聯網 (Internet of Things, IOT)等全新應用範疇的驅動下，無線通訊科技相信會經歷一場巨大的變革。但Rohde & Schwarz在這 80多年來累積的經驗及技術，相信能讓他們迎接無線通訊各種規新範所帶來的挑戰，我們亦衷心希望他們的研發能推動業界和科技的發展。',
    bodyZh: '',
    images: [
      {src: '/images/history/RS.jpg', altEn: '', altZh: ''},
      {src: '/images/history/RS.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2016/12/wtia-meet-our-member-%e7%be%85%e5%be%b7%e8%88%87%e6%96%bd%e7%93%a6%e8%8c%a8%e9%a6%99%e6%b8%af%e6%9c%89%e9%99%90%e5%85%ac%e5%8f%b8-rohde-schwarz-hong-kong-ltd/',
    featured: false,
  },
  {
    slug: '2017-asia-smart-app-summit-cum-award-presentation-ceremony',
    kind: 'milestone',
    year: 2017,
    month: '01',
    titleEn: '2017 – Asia Smart App Summit cum Award Presentation Ceremony',
    titleZh: '',
    bodyEn: 'With funding support from Create Hong Kong of the Government of the Hong Kong Special Administrative Region, the Asia Smart App Awards (formerly known as Asia Smartphone Apps Contest) aim to promote Hong Kong as a capital of Smart App in Asia by gathering the top industry experts across the region. A regional contest for Smart App, the Asia Smart App Awards successfully gather 11 participating countries/ regions in Asia, namely the Mainland, Israel, Japan, Korea, Malaysia, Singapore, Taiwan, Thailand, Indonesia, Philippines and Vietnam, etc. with the support from more than 20 industry organizations in Asia.',
    bodyZh: '',
    images: [
      {src: '/images/history/2017-Asia-Smart-App-Summit-cum-Award-Presentation-Ceremony-1-1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2017/01/2017-asia-smart-app-summit-cum-award-presentation-ceremony/',
    featured: false,
  },
  {
    slug: '2017-connected-city-conference',
    kind: 'milestone',
    year: 2017,
    month: '01',
    titleEn: '2017 – Connected City Conference',
    titleZh: '',
    bodyEn: 'WTIA organised the Connected City Conference and industry experts were invited to present their latest solutions on 5G, LoRaWAN, Sigfox and NB-IoT to build Hong Kong as a smart-city. This is the first Smart City event that centres on connectivity and the newest networks gathered in one setting to discuss IoT, data, security and all the essential ingredients for a truly empowering Smart Hong Kong.',
    bodyZh: '',
    images: [
      {src: '/images/history/2017-Connected-City-Conference-1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2017/01/2017-connected-city-conference/',
    featured: false,
  },
  {
    slug: '2017-develop-market-network-of-internet-of-vehicles-iov-in-mainland-china',
    kind: 'milestone',
    year: 2017,
    month: '01',
    titleEn: '2017 – Develop Market Network of Internet of Vehicles (IoV) in Mainland China',
    titleZh: '',
    bodyEn: 'Supported by BUD Fund, WTIA organised a series of events, including business networking event, public awareness seminar, study mission, to help Hong Kong enterprises capture opportunities to penetrate or expand business network across China.',
    bodyZh: '',
    images: [
      {src: '/images/history/2017-IoV-Mission-Tour-to-Chongqing-1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2017/01/2017-develop-market-network-of-internet-of-vehicles-iov-in-mainland-china/',
    featured: false,
  },
  {
    slug: '2017-hong-kong-ict-awards-best-mobile-app-award',
    kind: 'milestone',
    year: 2017,
    month: '01',
    titleEn: '2017 Hong Kong ICT Awards – Best Mobile App Award',
    titleZh: '',
    bodyEn: 'Supported by Office of the Government Chief Information Officer (OGCIO) and organized by WTIA, The Best Mobile Apps Awards aims to honour the best local mobile and wireless technology and application development, also to encourage further mobile and wireless technology and application development with enhanced creativity, design and commercial value.',
    bodyZh: '',
    images: [
      {src: '/images/history/2017-Hong-Kong-ICT-Awards-Best-Mobile-App-Award-1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2017/01/2017-hong-kong-ict-awards-best-mobile-app-award/',
    featured: false,
  },
  {
    slug: 'wtia-meet-our-member-yahoo-hong-kong',
    kind: 'member-story',
    year: 2017,
    month: '04',
    titleEn: 'WTIA Meet Our Member – 雅虎香港 (Yahoo Hong Kong)',
    titleZh: '',
    bodyEn: 'Interview with Tania Lau, Senior Director of Marketing & Communications, Yahoo Hong Kong\n\nhttps://hk.yahoo.com/\n\nPlease give us a bit of background to Yahoo Hong Kong and its current set up.\n\nYahoo is a global internet brand that had its beginnings in 1995 (22 years ago) as a web directory and portal, it has grown and evolved since into a world-recognized search-engine and go-to news and media website.The Hong Kong office was established in 1999 (18 years ago). While Yahoo Hong Kong is still wholly owned by Yahoo, we’re given a high level of autonomy in the way we run our business and this has provided the stability in which we operate. In Hong Kong, we aim to serve local users, partners, and key stakeholders. Our business centers around 3Cs; content (aggregation and marketing), communications (search, messaging tools), and commerce (consumer-to-consumer, business-to-consumer buy & sell).With our long history of strategic acquisitions, we do have many products but Yahoo offers nearly all of them for free. We no longer consider charging premium or even freemium models. In fact, our primary revenue source is from our advertising and marketing products and offerings (programmatic, data management & insights, native advertising, e-commerce and content, etc.). But to ensure relevancy to our clients and customers, we embrace the ‘go local’ approach. We don’t just translate whatever headquarters is doing and push it here. We make sure our offerings are always catered towards Hong Kongers. We have dedicated local teams for editorial, marketing, and advertising functions focused on driving a truly 360° solution for our customers.\n\nHow has the industry changed, and how is Yahoo Hong Kong looking to expand, what sort of new direction is the company taking?\n\nFrom what I can tell, digital marketing and advertising continues to face fast-paced changes locally. Content consumption patterns have shifted drastically and simply thinking “mobile first” could not cut through the noise. Our strategy for thriving and growing the business is thinking “video first” and integrating this with our programmatic solutions.\n\nWe have just launched Yahoo TV here in HK on April 24, a high-quality video livestreaming portal with all your news and need-to-know info in easily accessible and consumable video bites. This has already been piloted in Taiwan and has proven to be a major success. We can only see fantastic potential here for the Hong Kong market. My team has tested the waters already, we had the idea of bringing NFL to locals. It’s apparently very popular in the west, but most certainly not here, but we produced local content teaching Hong Kongers the rules of the game and how it is played. We live-broadcasted this on a Sunday night at 10pm, at peak, we topped 220,000 engaged viewers who were glued to the video for at least 8-10 minutes. The demand is evident, and Yahoo HK is working to supply that.We see we have a competitive edge in creating complete user journeys within 1 platform, this is a mainstream trend as users generally stick to only a select few platforms to obtain all the information or do all the work they need.\n\nWhat does your role as Senior Director of Marketing & Communications at Yahoo Hong Kong involve, can you tell us how you climbed the career ladder here?\n\nI started as Associate Marketing Manager and eventually moved into product marketing at Yahoo, working with really great products like Yahoo Personals (Yahoo! 友緣人) and Yahoo Answers (Yahoo! 知識), I did that for 3 years before I took on a more senior role overseeing consumer marketing, trade marketing, PR and market research, over the years, I rose through ranks through continuing my dedication to the team and culture at Yahoo HK, eventually landing my current role last year in April. Now as Senior Director of Marketing and Communications, I oversee the company’s brand and public relations strategy, as well business and consumer marketing programs to achieve our business objectives. I’ve been with Yahoo for over a decade already and to this day I still have the same mindset and learning crave I had as an intern. Yahoo is very much like the Shaolin Monastery, there are so many arts to master, yet so much dedicated training available to those who are passionate and rigorous about it. The company is huge on education and has worked strenuously in providing plenty of opportunity for on-the-job training, multimedia courses, internship programs like Yahoo University Program where participants get to visit and learn directly at Tumblr’s headquarters in New York.\n\nWhat’s your proudest and most memorable moment?\n\nYahoo has been running their internal annual Superstar Awards for 13 years. It allows employees to nominate each other for the award in recognition for exceptional performance and influence to the company. They present it to about 12 individuals out of the 11,000 global Yahoo staffers each year. So, I felt really, really honoured to have won last year! I was so happy of this achievement that instead of bringing my spouse to the award celebration, I brought my mom. I wanted her to be able to witness and be part of the culmination of love, happiness, and hard work I’ve experienced at Yahoo all these years. It is truly a proud and memorable moment in my life.\n\nIf you are to give one piece of advice to the Tania who just started at Yahoo, what would you say to her?\n\nBe open-minded and stay humble because it’s too easy to stereotype and generalize in this industry, holding an unassuming attitude does wonders for learning and adapting to daily changes and challenges!\n\n專訪：雅虎香港市場及傳訊資深總監 劉淑芬小姐\n\nYahoo Hong Kong的「本土」力量\n\nhttps://hk.yahoo.com/\n\n說到Yahoo，你會想起什麼？搜尋器、電郵、Yahoo拍賣、Yahoo GeoCities、Yahoo桌球和麻雀、Yahoo知識、Yahoo友緣人、Yahoo Messenger、Yahoo團購……雖然不同年代、不同背景的人可能有不同答案，但相信每個互聯絡的用家都有使用過它們的產品。\n\nYahoo於1995年正式在美國成立，4年後於1999年正式進駐香港。那個年代互聯網開始盛行，Yahoo香港提供一站式的資訊之餘更有免費電郵服務，簡單利落的設計及版面理所當然地成為互聯網用家的入門網站，引領他們出入多姿多采的互聯網世界。18年過去，Yahoo香港依舊是本地互聯網用家最常瀏覽的網站之一，其多元化的服務繼續令它們維持香港十大最高流量網站的地位，繼續陪伴香港互聯網用家成長。\n\n時光飛逝，Yahoo由當年新興的互聯網公司到這一刻已變成行內大師兄，主要業務由3C組成，Tania說：「第一是Content(內容)，這是我們很有信心的部分，無論是用戶需要的資訊，到與廣告客戶合作創造的內容行銷(Content Marketing)都很有經驗；第二是Communications(溝通工具)，透過不同工具，如搜尋引擎、電郵等幫助用戶與世界接軌；第三是Commerce(電子商貿)，亦是很多人忽略的部分，Yahoo購物正正是最好的例子。」\n\n18年不是短時時間，要長時間屹立於變幻無常的互聯網世界必定有其優勝之處。Tania加入Yahoo香港十多年，由助理產品經理開始，負責推廣搜尋器、Yahoo友緣人及Yahoo知識+等耳熟能詳的項目，到現在成為公司的市場及傳訊資深總監，對她而言，Yahoo香港的成功之處正正在於「夠落地」！\n\n「Yahoo香港比其他同業優勝之處是有本地營運團隊，有『本土自主權』，我們有自己的編輯人員、營銷及廣告團隊，因此會有更大彈性因此可以為用戶及廣告客戶提供最適合香港人的內容及方案。」Tania補充道：「同時，Yahoo香港在進佔市場已有電商部分，因此我們可為用家於同一平台上提供一站式服務，由內容部分至銷售部分都可透過Yahoo不同的渠道解決所需 。透過用戶在Yahoo平台上留下的大量足跡及數據，有助品牌更精準地抓緊目標用戶群。」\n\n作為其中一家於香港最悠久的互聯網公司，它們亦一直求變，為香港用家帶來切合需要的產品，從而吸納更多廣告客戶。\n\n「Video First是我們今年的主題。」Tania透露說：「影片、直播本身不是新鮮事。但隨著用戶習慣轉變，用戶已不滿足於圖片文字的內容傳遞，我們深信影音直播是內容製作、策展及行銷的主要制式。因此，Yahoo香港已於本月推出新項目 – 『Yahoo TV』。與其他影音直播平台提供用戶生成內容的直播方式不同，我們將會搜羅大量香港人高度關注的項目，尤其以本地體育及娛樂為首，更會製作自家的直播節目，為用戶帶來相對優質的節目。我亦相信影音與電子商貿的結合短期內會在香港會成為大趨勢。」\n\n「同時，這對於廣告客戶而言亦是一個新嘗試。Yahoo旗下的programmatic advertising 平台Brightroll和Gemini 均可以支援影音廣告，可協助廣告客戶精準針對目標觀眾，減低傳統漁翁撒網式的投放。我們希望透過這些工具，教育並協助廣告客戶了解他們消費者所需。」\n\n「加上近兩年推行的Push & Pull 組合廣告模式，一方面以Pull方式協助廣告客戶於搜尋結果增加曝光率，加上利用Native Advertising(原生廣告)以Push方式發放客戶資訊，另他們的產品更容易接觸到Yahoo用戶。」\n\nTania在Yahoo香港工作十數年，她見證了電子營銷行業的轉變，同時亦陪伴本地用戶、廣告商及策略夥伴一起成長。\n\n所謂十年磨一劍，從這些年的經驗，她寄語所有電子營銷從業員：「十年過去，我覺得自己在Yahoo仍然是一個實習生，互聯網及電子營銷的世界轉變太快，要常保持謙虛、開放、熱誠之心，不斷學習的態度，勇敢迎接每天的挑戰。」',
    bodyZh: '',
    images: [
      {src: '/images/history/Tania_2013.png', altEn: '', altZh: ''},
      {src: '/images/history/Tania_2013.png', altEn: '', altZh: ''},
      {src: '/images/history/Yahoo-1024x325-1.png', altEn: '', altZh: ''},
      {src: '/images/history/Image00001-768x512-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2017/04/wtia-meet-our-member-%e9%9b%85%e8%99%8e%e9%a6%99%e6%b8%af-yahoo-hong-kong/',
    featured: false,
  },
  {
    slug: 'wtia-meet-our-member-playnote',
    kind: 'member-story',
    year: 2017,
    month: '06',
    titleEn: 'WTIA Meet Our Member – Playnote',
    titleZh: '',
    bodyEn: '（中文版收錄於文章下方）\n\nInterview with Eric Yung, Founder and CEO, Playnote\n\nhttp://www.playnote.com\n\nMusic and technology looks like something hard to be put together, as music is something emotional and artistic but technology is all about calculation and science. Nevertheless, there is a tech company called Playnote, which is dedicated to combine music education with technology. Founded in 2010, Playnote has developed three products: AURALBOOK, SCALEBOOK and Rehearsal Partner. Both AURALBOOK and SCALEBOOK are designed to help student to prepare the aural and scale tests in the Associated Board of the Royal Schools of Music (ABRSM) exam, and Rehearsal Partner is designed to help student prepare for Hong Kong Schools Music Festival Competition.\n\nWhy does Playnote choose music education as their direction of development? What makes Playnote’s products special in educating music? We interviewed Mr. Eric Yung, Founder and CEO of Playnote, to answer these questions.\n\nPlaynote’s SCALEBOOK is the Grand Award winner in Hong Kong ICT Awards 2017: Best Mobile Apps Award\n\nAll the three products that are developed by Playnote are designed for music education, why did you choose that as the focus of Playnote?\n\nMainly because I am passionate about music. Before I founded Playnote, I have worked on many traditional jobs in the music industry. I was a performer, vocalist, composer, orchestra consultant and also a music teacher. And then one day, I realized these positions should not be the only things that I can contribute to the music industry. Thus, I chose to establish Playnote, a tech company that is dedicated to music education.\n\nLearning music is a phase that every musician has to go through, no matter what kind of music they are performing. Although music education is fundamental for the development of music, not many people are trying to provide an innovative solution on it. That is another reason why we chose music education as our development direction.\n\nBoth AURALBOOK and SCALEBOOK are designed to teach components included in music exams from different regions, including ABRSM exam, which is commonly taken by Hong Kong students. Why did you choose these as the focus of your products?\n\nIt’s because both aural test and scales are something that music teacher seldom want to teach (laughter). As a music teacher, it will be a relief for me if artificial intelligence (AI) can help me to accomplish these tasks and solve the issue that we music teacher are facing, and that is the goal for us to create these products.\n\nAnother reason why we develop AURALBOOK and SCALEBOOK is to solve a common problem in music industry – there are many people who want to learn music but do not have enough resources for them to do so. For example, they may not have time to take regular music lessons. Our solution is letting AI to do part of the teaching, and thus people can learn music with less resource.\n\nAI is a core component for Playnote’s product. Why is Playnote so keen to incorporate AI in music?\n\nMusic is not a rule-based thing, on the contrary, it is very subjective. In music exams, even if a music performance can be judged by the marking scheme, one examiner may find it excellent, another may not.\n\nMusic is not limited to 0 and 1, and there are many possibilities in between. Thus, traditional rule-based software would not be capable to handle music. That is why we incorporate AI in music – we want our products to evaluate a music performance in the same way humans do. When people listen to a musical performance, most of us will rely on our overall impression of the performance to judge if it is good or bad. We want AI to help us explain and induct this abstract “impression”.\n\nBoth AURALBOOK (released in 2012) and SCALEBOOK (released in 2017) have adopted AI in their features. How has AI advanced these past 5 years?\n\nAI has become more capable of human expression. Alongside with a real human voice commenting function, the AI in AURALBOOK can already give users an impression that there is a human instructor teaching them music. Still, as the way AI speak remains relatively straightforward, a user is able to find out eventually that it is a machine responding and not an actual person, therefore there is still some ways to go before the technology matures.\n\nAnd now in SCALEBOOK, when user completes a mock examination, the app will be able to provide a written report with details, comments and scores for each question, which is composed by the AI music examiner. As we have advanced the communication skill of the AI, it will be harder for the user to distinguish if the report is written by human or machine – and this is what we want to achieve. After all, music is a language for human. We always emphasize that our final goal is creating a program can communicate in a way with no difference to how humans talk.\n\nFor Playnote, what will be your next step in developing AI?\n\nThe three products that are developed by Playnote are all focused on musicianship such as intonation and tempo. For next step, we hope to develop an AI that can evaluate music performance.\n\nWe anticipate that AI can become a music critic in the future. By analyzing the details of a performance, the AI should be able to determine whether a piece of music is an outstanding performance, and explain why it is or why it isn’t. That’s the next level of AI we want to develop.\n\nLastly, can you share the proudest moment in your career?\n\nIt would be opportunities for moments like this now where I can talk about music to someone, to let more people learn about, appreciate and enjoy music, that is always the mission of Playnote.\n\n專訪：Playnote創辦人及行政總裁 容志偉先生\n\nhttp://www.playnote.com\n\n音樂與科技，表面上前者是感性的藝術，後者則是理性的運算與科技，兩者看似風馬牛不相及，互不相通。偏偏有一間科技公司，決意要將電子科技融入於音樂教育。這間科技公司名叫Playnote，由2010年創立至今，推出了AURALBOOK、SCALEBOOK以及同聲伴三件產品。其中AURALBOOK及SCALEBOOK分別針對英國皇家音樂學院考試中的音階及聽力測試部份而設，而同聲伴則協助學生準備香港校際音樂節的比賽項目。\n\n為什麼Playnote會選擇音樂教育作為公司的發展方向？Playnote研發的音樂教育產品又有何特別之處？我們訪問了Playnote創辦人及行政總裁容志偉先生，解答上述疑問。\n\nPlaynote開發的SCALEBOOK於2017香港資訊及通訊科技獎：最佳流動應用程式獎奪得大獎\n\nPlaynote由創辦至今，推出過的三件產品都是以音樂教育為賣點，為什麼當初會選擇以音樂及音樂教育作為主要的發展範疇？\n\n主要原因是個人取向吧。我自己是音樂出身的，「做音樂」也是我的興趣。傳統音樂範疇內的工作，由幕前的樂器演奏、唱歌，到幕後的工作例如作曲、擔任顧問到教鋼琴，這些我都曾經做過。其後覺得，音樂的世界應該不止於此，於是就嘗試踏出改變的一步，創辦了Playnote。\n\n至於為何會選擇發展音樂教育，因為我們覺得教育是其中不可或缺的一環。無論是專攻那種音樂類型的音樂家，都必然會經歷學習音樂的階段，音樂教育是當中最基本的東西。加上音樂教育是較少人著手去發展和創新的範疇，所以我們就決定以此為發展方向了。\n\nPlaynote的兩件產品AURALBOOK及SCALEBOOK，都是針對不同地區設立的音樂考試（例如大部份香港學生應考的英國皇家音樂學院ABRSM考試）而設計的。為什麼會選擇從這方面入手呢？\n\n聽力及音階測試的教學比較單一沉悶，是大部份音樂老師都不喜歡去教的東西（笑）。我自己也是個音樂老師，若這些部分有人工智能為我代勞，我也樂得輕鬆。解決自己正在面對的問題，就是我開發這些產品的初衷。\n\n另外，其中一個音樂界中常見的問題，就是有很多人想學音樂，卻未必有足夠資源去學習，例如不能有固定時間上音樂課。為了讓更多人有機會去學習音樂，我們提出的解決方法，就是讓部份的教學過程由人工智能去替代，令學生沒有足夠資源也能學習音樂。\n\n人工智能是構成Playnote產品的重要元素，為什麼會如此著重在音樂層面上投入人工智能技術？\n\n因為音樂並不是一樣以規則為基礎（rule-based）的東西，相反地，它是一樣很主觀的東西。就算我們的產品針對的已經是有評分準則可依循的考試項目，但同一段演奏，仍舊有機會出現一位考官覺得好，另一考官卻覺得不好的情況。\n\n音樂不止於0和1，中間還有更多的可能性。因此，傳統以規則為基礎去運作的程式，是無法處理如此複雜的東西。這就是人工智能在我們產品裡的功用－用人腦的角度去辨別一段演奏的好壞。人在聆聽演奏時，大部分時候都是以對該段演奏的整體印象，去評價該段演奏的好壞。歸納並解釋「印象」這種抽象的東西，就是我們產品藉人工智能想要達到的結果。\n\n由2012年推出的AURALBOOK到2017年的SCALEBOOK，兩件產品都有用到人工智能的技術。在這五年間，人工智能又有甚麼轉變和進步嗎？\n\n人工智能變得更能夠表達情感上的東西。當年AURALBOOK已經能夠造到基於用家的表演，即時以真人發聲的語音作出指導，予人像是有真人從旁指導的感覺。但是人工智能所產生的對話內容始終比較直接，用家多聽幾次後就不會覺得那麼像真了。\n\n到現在的SCALEBOOK，當用家透過程式進行模擬考試後，程式就能夠依據其表現寫一份文字報告，而且其寫法和內容更是像真得會讓人懷疑是不是背後有人在撰寫。這就是我們透過人工智能正在嘗試去達成的東西－讓人難以分清背後與用家對話的，究竟是人類還是機器。音樂始終是人類的語言。所以我們經常強調，當機器所給予的回應能夠像真人一樣時，才算是成功。\n\n對Playnote而言，人工智能發展的下一步會是怎樣的？\n\nPlaynote推出過的三件產品，針對的都是像音準及拍子之類的音樂家基本功（Musicianship）。接下來再進一步，就是希望人工智能能夠判斷歌曲的演奏是好是壞。\n\n我們希望往後的人工智能能夠像樂評家一樣，透過分析演奏家在表演裡所展現的彈奏速度、音量變化，以至表現出來的情感，判斷這次演奏出色與否。下一階段的人工智能，應要做到以上的分析，並且解釋到是基於怎樣的根據，才會作出這樣的判斷。\n\n最後，可以和我們分享一下你在事業上最自豪難忘的時刻嗎？\n\n其實就是現在這種能夠和你們聊天的時候了，因為在對話當中，我能夠教授很多關於音樂的知識給大家知道。將音樂傳授給更多人，就是Playnote想做的事情，也是我們的初衷了。',
    bodyZh: '',
    images: [
      {src: '/images/history/Eric-Yung-Playnote.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Playnote-Grand-Award-1024x683-1.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Eric-Yung-Playnote-2-1024x683-1.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Playnote-Grand-Award-in-Gala-Dinner-1024x769-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2017/06/wtia-meet-our-member-playnote/',
    featured: false,
  },
  {
    slug: 'wtia-meet-our-member-finfabrik',
    kind: 'member-story',
    year: 2017,
    month: '08',
    titleEn: 'WTIA Meet Our Member – FinFabrik',
    titleZh: '',
    bodyEn: 'Interview with Alex Medena, CEO of FinFabrik and Advisory Board Member of WTIA’s Fintech Core Focus Board.\n\nhttp://www.finfabrik.com\n\nHi Alex, can you tell us a little about your company and where its value lies?\n\nAlex: Sure, FinFabrik is a capital markets and wealth management technology solutions builder, comprising of three products; BrokerFabrik a fully integrated software system which caters to brokerage firms, AlgoFabrik which specializes in investment management using automation capabilities, and WealthFabrik which is a bespoke wealth management platform powered by machine learning layers for wealth management businesses. We basically started 11 months ago by acquiring the IP (intellectual property) of InvestLab, a HK-based retail brokerage platform focused on global retail trading. Imagine you have a brokerage license, RO, capital but you don’t have front, middle, and back end technology or the architecture to make financial advice and trades on the fly for your clients. This cloud-based technology aims to change all that: our solutions are B2B or B2B2C SaaS model. For us, it all boils down to customer experience. Now there are two types of retail-investment experiences; active trading where a client may have intrinsic motivation to buy stocks based on hearsay or market news, and then there’s passive trading where a client wants to save for future plans such as college, retirement or for a rainy day which is more under wealth management that today involves robo-advisors. FinFabrik deals with both kinds of experiences: we marry retail trading to wealth management. Unlike most startups; they start with an idea, a little capital, a powerpoint, they do an MVP and try to pitch to market and sell, we have technology from the get-go.\n\nWhat’s the current direction FinFabrik is taking to develop its business?\n\nAlex: We have a 1-2 year roadmap where we will bring more sophisticated data analytics tools and machine learning technologies to help end-users or end-investors to make the best decisions for their financial goals. It could be highly customized to the individual with risk-level assessments, bespoke research report and advice based on personal investment preferences and habits. Machine learning is aimed at helping customers learn much more about themselves than they would on their own, especially when they are overloaded with so much market information available everywhere.\n\nAnd where do you find challenges in your business?\n\nAlex: We do find that many brokerage firms and wealth management companies have either full or partial inflexibility in their infrastructure, meaning they are unable to shift or change due to technical complexities or costs. What we do is we built our solutions in modules and through APIs which could plug into their current existing infrastructure and deliver the functionalities they need. For example, a company may need portfolio management tools, fix connectivity or a dashboard for brokers; they can add that to their existing infrastructure.\n\nFinFabrik’s Team\n\nYour company stresses on something called “financial inclusion”, can you talk a little about that?\n\nAlex: Yes, this is absolutely important to us. There is the misconception that wealth management is only for the wealthy. Our mission, and myself as well as our other two cofounders strive to create a legacy to change things which include engaging and opening doors of financial education and wealth management access to under-served or unserved population; this includes middle-to-low income earners, minorities, women, or the financially illiterate who have the same kind of financial goals as the higher earners though at a lower scale. That scale doesn’t make it less important for the people in that “segment”. We are in 2017 and we still talk about financial inclusion which means we haven’t done enough in Fintech. The technology is there and the cost of running these platforms is lower than before.\n\nBanking in general and private banking in particular is a relationship based business though the latter is not scalable anymore and there is limit as to how many clients a relationship manager can service properly. Second, technology helps understand clients’ needs better and service them efficiently. Thirdly, and again technology plays a big part here, financial literacy is a key aspect particularly with gamification.\n\nAnd what is FinFabrik’s role in Fintech?\n\nAlex: While most companies tout the word “FinTech” and call themselves “FinTech companies” they are more “TechFin” companies. The technology is actually irrelevant and merely an enabler to enhance customer experiences and business processes. We honestly believe that FinTech should mean that finance comes first. We have a vision that is further than individualised solutions based on demographic segments: we want to create hyper personalised content catered to each and every individual and this could be done through AI (in the broad sense), but the end goal is not to build a business on machine learning or AI, the goal is to provide financial services to people in the best possible way. Therefore, we market ourselves as such and we are doing what we can in terms of public speaking and education to bring more awareness to easier financial management enabled by technology.',
    bodyZh: '',
    images: [
      {src: '/images/history/20626672_1300597533399940_4575181880632892801_o-e1663654361897.jpg', altEn: '', altZh: ''},
      {src: '/images/history/20643422_1300597410066619_149287315914085417_o-1024x768-1.jpg', altEn: 'FinFabrik’s Team', altZh: ''}
    ],
    legacyPath: '/2017/08/wtia-meet-our-member-finfabrik/',
    featured: false,
  },
  {
    slug: 'wtia-meet-our-member-pixel-networks-limited',
    kind: 'member-story',
    year: 2017,
    month: '09',
    titleEn: 'WTIA Meet Our Member – Pixel Networks Limited',
    titleZh: '',
    bodyEn: 'Interview with Pixel Network’s team: Kirill Nosov, CEO, Ralph Riley, CTO and David Turkington, Director of Technology\n\nhttp://www.pixel-networks.com/\n\nHi, can you please give us a bit of background of Pixel Networks and its current focus?\n\nDavid: Pixel Networks came to Hong Kong 2 years ago. In response to the smart city initiative that was proposed by the HKSAR Government, we decided to set up a business and transform Hong Kong into a smart city.\n\nThere are several different types of technology that can be applied to build a smart city. For Pixel, we have chosen LoRa as our focus. One of the main reasons we pick LoRa is because it is fully developed ecosystem already, and it has been globally developed in many regions, such as Europe and America. As an open standard, LoRa has also collaborated with many major companies in the field. We adopted this technology and brought its ecosystem to Hong Kong.\n\nRecently Pixel Networks has a collaboration with Actility to build the Hong Kong’s first LoRaWAN network, is it another step for Pixel to further develop the ecosystem in Hong Kong?\n\nDavid: That is correct. Actually, our partnership with Actility was lined up by Cisco, as we are a Cisco Preferred Solution Partner for providing equipment to build networks and Actility is one of the major network providers of LoRaWAN for Cisco too.\n\nWhat’s the field Pixel Networks is currently focusing on to develop its business?\n\nDavid: We are working with serval building management companies by constructing wireless networks and monitoring system in their buildings.\n\nRalph: For example, many of the buildings are already 10-20 years old so their infrastructure did not have in-built monitoring system. Therefore, we came along and provided IoT solutions for monitoring in different aspects; including temperature control and air conditioning. We also offered solutions for tracking too. After talking to many different people, we also came up with new ideas for components to help build smart city, such as smart trashcans, smart street lights and smart traffic signs.\n\nWhere do you find challenges when building the LoRaWAN network and developing business in Hong Kong?\n\nDavid: One of the challenges we found in Hong Kong is from regulatory standpoint. In these years, we have spent a significant amount of time to deal with HK Government. The good news is Government started to be more aware of IoT and will issue a new license called “Public Wireless Internet of Things Service Licence” (WIoT Licence) soon. The License will give us greenlight to operate and provide IoT services.\n\nRalph: We are also requested by the regulator to examine if there is any harmful interference existing between LoRa and Radio-frequency identification (RFID). We have completed the assessment in May and proved that no harmful interference will exist. The report is available in Office of the Communications Authority (OFCA) website too.\n\nDavid: We do find that there is more awareness in IoT in Hong Kong. I think in the beginning, it is a little bit awkward to present our business. After gaining experience from our first year, we started to adjust our presentation, including involving an introduction to IoT and providing more solutions about IoT that can be incorporated clients’ businesses.\n\nPixel Networks will speak in Connected City Conference at 9 November, 2017. Join us for the insightful conversation about 5G and IoT!',
    bodyZh: '',
    images: [
      {src: '/images/history/Pixel-Networks.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Screenshot_1-1-1024x413-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2017/09/wtia-meet-our-member-pixel-networks-limited/',
    featured: false,
  },
  {
    slug: 'wtia-meet-our-member-mtel-limited',
    kind: 'member-story',
    year: 2017,
    month: '10',
    titleEn: 'WTIA Meet Our Member – Mtel Limited',
    titleZh: '',
    bodyEn: '專訪：黃明威先生 (Willy), CEO of Mtel Limited, Mtel Lab Limited & Weying Mtel Limited\n\nhttp://www.mtelnet.com\n\n自1999年以來，MTel Limited (MTel)一直跟整個跟ICT 行業一起演變成長。由SMS訊息推廣到遇上3G普及化和後來的APP，MTel CEO 黃明威先生 (Willy) 笑說業務總離不開手提電話 (mobile)。說罷，Willy隨手拿出當年有關SMS的剪報，興奮地訴說著前塵往事。如果唔係Steve Jobs繼而有iPhone的出現，可能MTel仍舊專注於跟東南亞的電訊商合作，將手機上網普及。現時，MTel於香港、廣州及台灣皆有自己的團隊。\n\n在2009年短短一年間，Willy憑著跟電訊商合作的十年經驗，收到不同銀行的查詢如何開發及設計手機應用程式。當時，MTel成功轉型，專注為十多間銀行製造其手機應用程式，後來亦涉足保險公司的程式開發。MTel現時做solutions員工有130人。\n\n除了經營不同行業的產品開發，Willy亦創立了MTel Lab以研發自家產品，探索各種商業模式的可行性。其中令他自豪的是上網買戲飛無手續費，片商利潤卻增加了。原因有二：\n\n1. 透過大數據 (Big Data) 令一般人睇多左戲，連繫類同電影喜好口味的人；\n\n2. 透過社會影響 (social influence) 讓每個交易數量提高，因入戲院睇戲是一個群體活動，朋友間以whatsapp推介，量多而享有value-added優惠\n\n雖然在Offline做不到，但在手機的世界卻可以。在市場上逐步逐步實現出來，並需要電影公司及戲院的支持和配合。\n\nWilly喜歡的事物不少，對任何新事物都抱有興趣，但他汲取新知識未必靠書本雜誌。他很喜歡跟人聊天，亦很喜歡開會。透過不斷重複自己的說話，可以改善想法。工作上也一樣，很喜歡傾計互動溝通，分享不同想法，並同時從別人身上學習如何突圍而出。\n\n另外，他亦很喜歡做運動，每星期做三日健身每次兩小時，一場籃球一場足球，再加一場open league比賽，不同類型的運動都會玩。雖然每日時間有限，但「當你喜歡某事物，你不會覺得辛苦」Willy如是道。際遇就如滑水，無風無浪的話前行不難，但浪到時機到時要有能力應付才可以跳得更高更遠，所以一定要做好準備，不止看眼前的東西。',
    bodyZh: '',
    images: [
      {src: '/images/history/DSC04236-chosen.jpg', altEn: '黃明威先生 (Willy)', altZh: ''},
      {src: '/images/history/DSC04236-chosen-800x609.jpg', altEn: '黃明威先生 (Willy)', altZh: ''}
    ],
    legacyPath: '/2017/10/wtia-meet-our-member-mtel-limited/',
    featured: false,
  },
  {
    slug: '2018-develop-market-network-of-internet-of-vehicles-iov-in-mainland-china',
    kind: 'milestone',
    year: 2018,
    month: '01',
    titleEn: '2018 – Develop Market Network of Internet of Vehicles (IoV) in Mainland China',
    titleZh: '',
    bodyEn: 'Supported by BUD Fund, WTIA organised a series of events, including business networking event, public awareness seminar, study mission, to help Hong Kong enterprises capture opportunities to penetrate or expand business network across China.',
    bodyZh: '',
    images: [
      {src: '/images/history/2018-Develop-Market-Network-of-Internet-of-Vehicles-IoV-in-Mainland-China.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2018/01/2018-develop-market-network-of-internet-of-vehicles-iov-in-mainland-china/',
    featured: false,
  },
  {
    slug: '2018-meeting-with-yc-partner-eric-migicovsky-how-to-apply-successfully-for-y-combinator',
    kind: 'milestone',
    year: 2018,
    month: '01',
    titleEn: '2018 – Meeting with YC Partner – Eric Migicovsky: “How to apply successfully for Y Combinator?”',
    titleZh: '',
    bodyEn: 'In partnership with ZEROZONE, the Hong Kong’s startup base, WTIA and Zerozone have invited Eric Migicovsky, partner of Y Combinator to talk about how to get into YC. Y Combinator, also known as the “Fixed Point Combinator”, is the most prominent accelerator in Silicon Valley. Eric Migicovsky is the Founder and CEO of Pebble Technology (YC W11), which was acquired by Fitbit in 2016. In April 2012, Eric and his team launched Pebble on Kickstarter, where it became the most successful crowdfunded project in Kickstarter’s history. Pebble sold over 2,000,000 watches.',
    bodyZh: '',
    images: [
      {src: '/images/history/2018-Meet-with-Y-Combinator.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2018/01/2018-meeting-with-yc-partner-eric-migicovsky-how-to-apply-successfully-for-y-combinator/',
    featured: false,
  },
  {
    slug: '2018-taipei-iot-business-delegation-tour',
    kind: 'milestone',
    year: 2018,
    month: '01',
    titleEn: '2018 - Taipei IOT Business Delegation Tour',
    titleZh: '',
    bodyEn: 'Supported by Taipei Economic and Cultural Office, WTIA organised the Taipei IoT Business Delegation Tour, with the aim to expand the cross-border networking and exchange IoT knowledge between Hong Kong and Taiwan, as well as providing a better understanding of Taiwan outstanding development on Smart City sector. Learning the latest solutions on 5G, IoT and IoV is the key session of the trip, industry experts were invited to share the knowledge and experiences to delegates. The visiting delegates from Hong Kong consisted of web hosting providers, software vendors, hardware vendors, E-Commerce companies and Telecommunications Companies.',
    bodyZh: '',
    images: [
      {src: '/images/history/2018-Taipei-Delegation-Tour-1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2018/01/2018-taipei-iot-business-delegation-tour/',
    featured: false,
  },
  {
    slug: '2019-a-5g-revolution-what-does-it-mean-for-me',
    kind: 'milestone',
    year: 2019,
    month: '01',
    titleEn: '2019 – A 5G Revolution: What does it mean for me?',
    titleZh: '',
    bodyEn: 'Hong Kong is actively deploying 5G Application in all areas. How will it affect the quality of life and improve the social efficiency in the near future? WTIA joined hands with The Hong Kong Productivity Council (HKPC), invited industry export to share and exchange views on 5G application, the latest global trends, 5G systems for new application and the new business models of 5G Era.',
    bodyZh: '',
    images: [
      {src: '/images/history/2019-A-5G-Revolution-What-does-it-mean-for-me_-1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2019/01/2019-a-5g-revolution-what-does-it-mean-for-me/',
    featured: false,
  },
  {
    slug: '2019-asia-smart-app-awards-2018-2019',
    kind: 'milestone',
    year: 2019,
    month: '01',
    titleEn: '2019 – Asia Smart App Awards 2018/ 2019',
    titleZh: '',
    bodyEn: 'With funding support from Create Hong Kong of the Government of the Hong Kong Special Administrative Region, the Asia Smart App Awards (formerly known as Asia Smartphone Apps Contest) aim to promote Hong Kong as a capital of Smart App in Asia by gathering the top industry experts across the region. A regional contest for Smart App, the Asia Smart App Awards successfully gather 13 participating countries/ regions in Asia, namely the Israel, Indonesia, Japan, Korea, Mainland, Malaysia, Myanmar, Philippines, Singapore, Sri Lanka ,Taiwan, Thailand, and Vietnam, etc. with the support from more than 20 industry organizations in Asia.',
    bodyZh: '',
    images: [
      {src: '/images/history/2019-Asia-Smart-App-Awards-2018_-2019-1-1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2019/01/2019-asia-smart-app-awards-2018-2019/',
    featured: false,
  },
  {
    slug: '2019-joint-ict-spring-dinner-2019',
    kind: 'milestone',
    year: 2019,
    month: '01',
    titleEn: '2019 – Joint ICT Spring Dinner 2019',
    titleZh: '',
    bodyEn: 'To welcome the New Year of The Pig, Hong Kong Wireless Technology Industry Association (WTIA) , Hong Kong Information Technology Federation (HKITF), Hong Kong Retail Technology Industry Association (RTIA) organised Joint ICT Spring Dinner. This event was also supported by some other ICT associations.',
    bodyZh: '',
    images: [
      {src: '/images/history/2019-Joint-ICT-Spring-Dinner-2019-1.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2019/01/2019-joint-ict-spring-dinner-2019/',
    featured: false,
  },
  {
    slug: '2019-techconnect-conference-festival',
    kind: 'milestone',
    year: 2019,
    month: '01',
    titleEn: '2019 – TechConnect Conference & Festival',
    titleZh: '',
    bodyEn: 'With the advent of the 5G era, IoT has been the hottest topic in the world. IoT is the key to connect all things, it is next industrial revolution which is now changing the quality of living in many ways that were never imagined before. This technology is undoubtedly an economic driver in the new era and for all industries, but a new model of development.\n\nTo assist Hong Kong SMEs to connect with global industry and enhance their capabilities on IoT technologies, cyber security, related standards and regulation, WTIA had organised a full-day conference along 7 separate workshops, invited the most famous and reputable leaders in the cybersecurity & IoT industry to provide the relevant solving skill to Hong Kong SMEs about those technologies.',
    bodyZh: '',
    images: [
      {src: '/images/history/2019-TechConnect-Conference-_-Festival.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2019/01/2019-techconnect-conference-festival/',
    featured: false,
  },
  {
    slug: '2020-asia-smart-app-awards-2020',
    kind: 'milestone',
    year: 2020,
    month: '01',
    titleEn: '2020 – Asia Smart App Awards 2020',
    titleZh: '',
    bodyEn: 'With funding support from Create Hong Kong of the Government of the Hong Kong Special Administrative Region, the Asia Smart App Awards (formerly known as Asia Smartphone Apps Contest) aim to promote Hong Kong as a capital of Smart App in Asia by gathering the top industry experts across the region. A regional contest for Smart App, the Asia Smart App Awards successfully gather 15 participating countries/ regions in Asia, namely the Cambodia, Israel, India, Indonesia, Japan, Korea, Mainland, Malaysia, Myanmar, Philippines, Singapore, Sri Lanka ,Taiwan, Thailand, and Vietnam, etc. with the support from more than 30 industry organizations in Asia.',
    bodyZh: '',
    images: [
      {src: '/images/history/2020-ASA--scaled.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2020/01/2020-asia-smart-app-awards-2020/',
    featured: false,
  },
  {
    slug: '2020-hong-kong-ict-awards-ict-startup-award',
    kind: 'milestone',
    year: 2020,
    month: '01',
    titleEn: '2020 - Hong Kong ICT Awards – ICT Startup Award',
    titleZh: '',
    bodyEn: 'Supported by Office of the Government Chief Information Officer (OGCIO) and organized by WTIA, ICT Startup Award aims at discovering and recognising the outstanding local ICT startup companies which focus on software, hardware and social innovation areas and, reward their distinguished development based on its growth, innovation, creativity, functionality, market potential and performance.',
    bodyZh: '',
    images: [
      {src: '/images/history/2020-ICT-Awards-scaled.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2020/01/2020-hong-kong-ict-awards-ict-startup-award/',
    featured: false,
  },
  {
    slug: 'postpone-asia-smart-app-awards-2020',
    kind: 'milestone',
    year: 2020,
    month: '03',
    titleEn: '[2nd Call for Applications] Asia Smart App Awards 2020',
    titleZh: '',
    bodyEn: 'Organised by the Hong Kong Wireless Technology Industry Association and sponsored by Create Hong Kong of the Government of the Hong Kong Special Administrative Region, the Asia Smart App Awards 2020 (the Award) has commenced its second round of calling for applications to invite online nomination of excellent and innovative smart apps designed for and used in Asian markets for various awards. In order to provide sufficient time for interested parties to prepare for their participation in the Awards, DEADLINE has been extended to 10 June 2020, 23:59 (GMT+8).\n\nAll apps irrespective of Web, Hybrid or Native App are welcomed to participate in the Award!\n\nWhat are you waiting for? Please click the following webpage for application.\n\n?http://contest2020.bestasiaapp.hk/',
    bodyZh: '',
    images: [
      {src: '/images/history/ASA2020-banner_OP_02-scaled.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2020/03/postpone-asia-smart-app-awards-2020/',
    featured: false,
  },
  {
    slug: 'postpone-hong-kong-ict-awards-2020-ict-startup-award',
    kind: 'milestone',
    year: 2020,
    month: '03',
    titleEn: '[POSTPONE] Hong Kong ICT Awards 2020 - ICT Startup Award',
    titleZh: '',
    bodyEn: 'Dear Partners and Friends,\n\nWe regret to inform you that all assessments and judging, along with the awards presentation ceremony of Hong Kong ICT Awards 2020 – ICT Startup Award originally scheduled for 3 Apr 2020, has been postponed until further notice.\n\nLatest information of ICT Startup Award can be viewed at : https://www.ictstartup.org/\n\nIf there is any question, please contact Ms Kylie Li via (2989 9164, [email protected]).',
    bodyZh: '',
    images: [
      {src: '/images/history/ICT-StartUp.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2020/03/postpone-hong-kong-ict-awards-2020-ict-startup-award/',
    featured: false,
  },
  {
    slug: 'postpone-joint-ict-spring-dinner-2020',
    kind: 'milestone',
    year: 2020,
    month: '03',
    titleEn: '[POSTPONE] Joint ICT Spring Dinner 2020 (香港資訊及通訊科技業界 庚子鼠年聯合春茗)',
    titleZh: '',
    bodyEn: 'Joint ICT Spring Dinner 2020 (香港資訊及通訊科技業界 庚子鼠年聯合春茗) which will be organized by Hong Kong Information Technology Federation (HKITF), Hong Kong Internet Service Providers Association (HKISPA) and Hong Kong Wireless Technology Industry Association (WTIA), has been postponed until further notice.',
    bodyZh: '',
    images: [
      {src: '/images/history/SPRING-DINNER.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2020/03/postpone-joint-ict-spring-dinner-2020-%e9%a6%99%e6%b8%af%e8%b3%87%e8%a8%8a%e5%8f%8a%e9%80%9a%e8%a8%8a%e7%a7%91%e6%8a%80%e6%a5%ad%e7%95%8c-%e5%ba%9a%e5%ad%90%e9%bc%a0%e5%b9%b4%e8%81%af%e5%90%88/',
    featured: false,
  },
  {
    slug: 'postpone-tokyo-industry-4-0-training-programme',
    kind: 'milestone',
    year: 2020,
    month: '03',
    titleEn: '[POSTPONE] ‘Tokyo ‘Industry 4.0’ Training Programme’',
    titleZh: '',
    bodyEn: 'The ‘Tokyo ‘Industry 4.0’ Training Programme’ originally scheduled for 16-19 March 2020 has been postponed. We target to reschedule it to October 2020 and the exact rescheduling will be announced in March.',
    bodyZh: '',
    images: [
      {src: '/images/history/TOKYO.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2020/03/postpone-tokyo-industry-4-0-training-programme/',
    featured: false,
  },
  {
    slug: 'smartone-press-release-ericsson-5g',
    kind: 'press-release',
    year: 2020,
    month: '03',
    titleEn: '[SmarTone - Press Release] SmarTone 選用愛立信5G 共同推動香港5G數碼化',
    titleZh: '',
    bodyEn: '[pdf-embedder url=”/wp-content/uploads/2020/05/SmarTone-選用愛立信5G-共同推動香港5G數碼化_web.pdf”]\n\n[pdf-embedder url=”/wp-content/uploads/2020/06/SmarTone-selects-Ericsson’s-5G-to-power-digitalization-in-Hong-Kong_web.pdf”]',
    bodyZh: '',
    images: [],
    legacyPath: '/2020/03/smartones-press-release-smartone-%e9%81%b8%e7%94%a8%e6%84%9b%e7%ab%8b%e4%bf%a15g-%e5%85%b1%e5%90%8c%e6%8e%a8%e5%8b%95%e9%a6%99%e6%b8%af5g%e6%95%b8%e7%a2%bc%e5%8c%96/',
    featured: false,
  },
  {
    slug: 'it-sme-anti-epidemic-fund-appeal',
    kind: 'milestone',
    year: 2020,
    month: '04',
    titleEn: '[新聞稿] 疫情重創IT中小企 初創資金鏈斷裂急須救亡 莫乃光及IT界團體促抗疫基金加碼援助',
    titleZh: '',
    bodyEn: '【新聞稿】\n\n疫情重創IT中小企 初創資金鏈斷裂急須救亡莫乃光及IT界團體促抗疫基金加碼援助\n\n（2020年4月9日，香港）政府昨日公布第二輪防疫抗疫基金，涉及1375億元。新措施包括向合資格企業提供五成工資補貼，資助上限為每月9,000元，另外就支援科技業，政府亦推出5億元的網上營商計劃，支援企業利用科技服務便利員工在家工作。\n\n立法會資訊科技界議員莫乃光今日聯同業界團體代表、科技企業及初創企業創辦人及電競業組織舉行記者會回應新措施，批評政府對業界支援仍然不足，促請當局為科技界提供更多即時援助，包括向IT公司提供一筆過10萬元資助、增撥10億元提供租金和薪金補貼，並優先採購本地科技方案和產品，拯救面臨財務懸崖的中小企和初創企業。\n\n莫乃光議員表示：『新措施錦上添花有餘，雪中送炭不足。薪金補貼及購買科技方案的新資助能對業界起有一定幫助，但對於大量未能受惠早前公佈半年租金寬免的科技界中小企和初創企業而言，新一輪抗疫基金仍然未提供租金方面的及時雨，IT業危機已逼在眉睫。』\n\n早於新一輪抗疫措施公布之前，莫乃光與專業議政其他議員共同向政府提交建議，針對IT界和初創的需要，提出包括直接每家合資格IT公司津貼10萬、設立特快貸款等建議，前日再向創科局局長提出建議，要求撥出10億助香港IT界中小企應付租金和員工薪金開支六個月，讓IT公司度過難關避免出現大規模倒閉和裁員潮，幫助業界化危為機。\n\n香港資訊科技商會榮譽會長方保僑及香港互聯網服務供應商協會主席葉旭輝在記者會上指出第二輪防疫基金措施對科技界幫助有限。方表示新措施遠水未能救近火，自由工作者未能受惠，認爲不應只救交稅人士。\n\n葉旭輝表示數據中心及雲端服務供應商等等生意一落千丈，而受疫情影響，香港電子科技商會主席蔡劍誠同樣表示IT中小企正面對生意下滑，香港零售科技商會執行總監周俊賢亦一併指出零售科技市道轉差，訂單量和成交額急跌。蔡劍誠呼籲政府加大採購科技方案，加速政府數碼轉型，而香港無線科技商會主席羅國明則建議政府重新評估政府承辦商名單，優先採購本地公司提供的服務及商品，為本地企業創造更多商機。他續建議政府放寬、簡化及加快批核各項創科相關的資助項目。\n\n大量初創企業疫情以來現金流斷裂，恐面對沒頂之災。羅國明表示有初創企業投資者暫停投資，令不少初企面對即時融資困難。科學園科培網絡會長李治緯認爲政府工資補貼作用不大，因爲研發人員普遍薪資遠超補貼上限，建議為初企開設特快批核貸款、政府亦應提注資為初企業提供更有彈性的，並加快批出資助，為初企解決燃眉之急。\n\n經營共享工作空間的Ooosh Limited行政總裁鄭煒恆指出政府工資補貼來得太遲，有旗下企業一月已解僱大部份員工，初創企業已出現裁員潮。而政府早前的6個月免租令其餘初創公司未能受惠，做法不公平。他指出租金佔初創企業營運一大部分，租金補貼絕對有逼切性。\n\n電競界同樣受疫情影響出現嚴重經營困難。香港電子競技體育總會副主席鄺君賢、電競初創公司Godzpeed Autosport聯合創辦人及行政總裁羅賢及九龍電競館營運經理林鳳儀表示受疫情及禁聚令影響，電競業由電競公司、電競隊營運公司、業餘電競戰隊俱樂部到電競製作公司及培訓公司等各階層均大受打擊，估計九成以自由身形式工作的直播主及製作公司從業員已被裁減。他們期望政府提供更多直接資助，向電競業界提供一筆過撥款並協助轉型網上業務。\n\n莫乃光總結指：『政府多年為推動創新科技投入大量公帑，目前出現海嘯式危機，政府應帶頭增加對本地科技服務的需求，並為IT界企業提供更直接的即時援助，否則疫情令業界元氣大傷，將浪費多年投資和流失本地人才。』莫議員已去信要求安排業界與創新及科技局局長楊偉雄會面商討所需援助。',
    bodyZh: '',
    images: [
      {src: '/images/history/20200409-it-sme-relief-press-conference-05.jpg', altEn: '', altZh: ''},
      {src: '/images/history/20200409-it-sme-relief-press-conference-01.jpg', altEn: '', altZh: ''},
      {src: '/images/history/20200409-it-sme-relief-press-conference.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2020/04/%e6%96%b0%e8%81%9e%e7%a8%bf-%e7%96%ab%e6%83%85%e9%87%8d%e5%89%b5it%e4%b8%ad%e5%b0%8f%e4%bc%81-%e5%88%9d%e5%89%b5%e8%b3%87%e9%87%91%e9%8f%88%e6%96%b7%e8%a3%82%e6%80%a5%e9%a0%88%e6%95%91%e4%ba%a1/',
    featured: false,
  },
  {
    slug: 'smartone-press-release-5g-service-launch',
    kind: 'press-release',
    year: 2020,
    month: '05',
    titleEn: '[SmarTone - Press Release] SmarTone 5G 服務啟動 網絡覆蓋全港至廣 帶動香港智慧城市發展',
    titleZh: '',
    bodyEn: 'SmarTone 正式在香港推出 5G 服務，帶來極速 5G 網 絡，於室內室外提供至廣覆蓋。SmarTone 5G 亦為不同客戶群及企業推出一系列創新 5G 服務及應用。配合高競爭力及具彈性的 5G 服務計劃，SmarTone 致力為客戶提供 全城最佳的整體 5G 網絡體驗。\n\n[pdf-embedder url=”/wp-content/uploads/2020/05/SmarTone-5G-服務啟動-網絡覆蓋全港至廣-帶動香港智慧城市發展.pdf”]\n\n[pdf-embedder url=”/wp-content/uploads/2020/06/SmarTone-launches-5G-service-with-the-citys-widest-network-coverage-to-spearhead-smart-city-development-in-Hong-Kong.pdf”]',
    bodyZh: '',
    images: [
      {src: '/images/history/Photo-1-scaled.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Photo-2-scaled.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Photo-5.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Photo-4.jpeg', altEn: '', altZh: ''},
      {src: '/images/history/Photo-3.jpeg', altEn: '', altZh: ''},
      {src: '/images/history/Photo-1-scaled.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Photo-2-scaled.jpg', altEn: '', altZh: ''},
      {src: '/images/history/Photo-3.jpeg', altEn: '', altZh: ''},
      {src: '/images/history/Photo-4.jpeg', altEn: '', altZh: ''},
      {src: '/images/history/Photo-5.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2020/05/smartone-press-release-smartone-5g-%e6%9c%8d%e5%8b%99%e5%95%9f%e5%8b%95-%e7%b6%b2%e7%b5%a1%e8%a6%86%e8%93%8b%e5%85%a8%e6%b8%af%e8%87%b3%e5%bb%a3-%e5%b8%b6%e5%8b%95%e9%a6%99%e6%b8%af%e6%99%ba/',
    featured: false,
  },
  {
    slug: 'asia-smart-app-workshop-ux-ui-more-than-you-think',
    kind: 'milestone',
    year: 2020,
    month: '10',
    titleEn: 'Asia Smart App Workshop - UX/UI More Than You Think',
    titleZh: '',
    bodyEn: 'User Experience and User Interface (UX/UI) design is more than creating good looking products. You will explore the valuable insights and experience with which design techniques that can help developer to make better apps, with more human-centred, innovative and funny elements.\n\nIf you are planning to have your own mobile application, website, or custom web app or have any type of query or concern regarding its concept, technical know-how, the best way to get it done then don’t hesitate to join the Workshop.\n\nDate: 8th September 2020 (Tuesday) Time: 3:00 – 5:00pm (GMT+8) Format: Live Webinar Language: English\n\nSpeakers:\n\nWebinars replay:\n\nPresentation Deck:\n\n[pdf-embedder url=”/wp-content/uploads/2020/09/Keith-Li-Brief-intro-to-UX”]\n\n[pdf-embedder url=”/wp-content/uploads/2020/09/Deck_UIUX_MoreThanYouThink_V4″]',
    bodyZh: '',
    images: [],
    legacyPath: '/2020/10/asia-smart-app-workshop-ux-ui-more-than-you-think/',
    featured: false,
  },
  {
    slug: 'the-strategies-for-expanding-global-internet-of-things-iot-markets',
    kind: 'milestone',
    year: 2020,
    month: '10',
    titleEn: 'The Strategies for Expanding Global Internet of Things (IoT) Markets',
    titleZh: '',
    bodyEn: 'Internet of things (IoT) is the key enabler to connect all things, it is next industrial revolution which is now changing our living in many ways that we never imagined before. Also, the 5G service in parts of Hong Kong was launched on 1 April 2020. This helps to enable most internet of things (IoT) and as smart city is essentially relied on IoT to function, 5G and smart city is inextricably linked.\n\nTo develop IoT locally, it is beneficial to capitalise on the global technological infrastructure, such as the rapidly developing 5G mobile network that enables a faster data processing time and a connection of more IoT devices. It is also imperative to make alignments with the current standards regarding the IoT technologies and cyber security.\n\nHong Kong has many talents enterprises in the information & communication technology (ICT) and electronic industries; however, the development of IoT products is affected by the inadequate connections between electronic and ICT industries. In addition, both industries are lacking in the resources to interpret the standards regarding to the IoT technologies and cyber security.\n\nTo improve this situation, Hong Kong Wireless Technology Industry Association (WTIA) consigned Hong Kong Productivity Council (HKPC) to obtain the approval on SME Development Fund from Trade and Industry Department to launch two seminars, standards studies, ten technical workshops and a one-day TechConnect conference, supporting the enterprise to gain the first hand information about the latest standards and IoT technologies. This could help to tighter the connections between the enterprises and their counterparts worldwide, and ultimately augment their competitiveness.\n\nGuide Book:\n\n*For any comments of the Guide Book, please feel free to fill in and submit the survey to [email protected].\n\n[pdf-embedder url=”/wp-content/uploads/2020/11/The-Strategies-for-Expanding-Global-IoT-Markets1.pdf”]\n\n[pdf-embedder url=”/wp-content/uploads/2020/10/Survey-for-guidebook.pdf”]\n\n*Any opinions, findings, conclusions or recommendations expressed in this material / event (or by members of the Project team) do not reflect the views of the Government of the Hong Kong Special Administrative Region, Trade and Industry Department or the Vetting Committee of the SME Development Fund and the Dedicated Fund on Branding, Upgrading and Domestic Sales (Organisation Support Programme).',
    bodyZh: '',
    images: [],
    legacyPath: '/2020/10/the-strategies-for-expanding-global-internet-of-things-iot-markets/',
    featured: true,
  },
  {
    slug: 'simcardregistration',
    kind: 'milestone',
    year: 2021,
    month: '03',
    titleEn: '[即時發布] 香港無線科技商會就電話智能卡實名登記制度之意見書',
    titleZh: '',
    bodyEn: '即時發布\n\n香港無線科技商會就電話智能卡實名登記制度之意見書\n\n政府擬制定電話智能卡實名登記制度，用以打擊不法之徒透過儲值電話卡的匿名手段從事的違法行為。新措施下規管作為儲值卡用戶的公司個體只可向每個持牌人登記不多於三張儲值卡，措施亦規定持牌人如流動網絡商或電訊商須肩負登記用戶資料的責任，建立相關系統或數據庫以核對並貯存用戶個人資料。香港無線科技商會明白規管儲值卡之緣由，惟擬定的新措施或有機會對業界於業務發展及技術開發上造成阻礙。政府就引入電話智能卡實名登記制度的安排展開公眾諮詢，本會謹此反映意見，冀予以慎重考慮。\n\n一、措施條例細節欠奉及諮詢期過短\n\n1. 受規管的電話卡類型指引欠清晰\n\n擬議的新措施並未為受規管的電話卡類型作出清晰明確的定義。預付儲值電話卡種類繁多如本地卡﹑國際卡及漫遊卡，建議中並未清楚列明當中哪一類電話卡應受新措施的監管。另外，建議中並未有提及規管措施是否只局限於人對人傳輸的電話卡，而對於純機器類型連接及機器對人傳輸的電話卡類型的安排則尚未有清楚確切的界定及相關建議，然而，後者這兩類電話卡在進行技術研發及測試上十分普遍，故細節上的不明瞭難免使業界對於新措施抱有存疑。\n\n2. 新措施茲事體大，諮詢期不足兩月\n\n智能電話卡應用層面相當廣泛，並非僅局限資訊科技業界。而於對業界而言，電話卡的應用在開發物聯網等先進技術有著不可或缺的重要性，並多見於系統測試等方面，然而，新措施下對於公司可擁有的電話卡數量進行規管，無疑是壓縮企業創科空間，削減香港作為亞洲創科樞紐的競爭力。本會樂見政府將原定諮詢期延長二十天至三月二十日，然而，措施對於香港創科長遠發展有深遠影響，故各界亦冀盼有更多的時間和空間以了解新措施細則。\n\n1. 未有明確指引協助電訊商核對用戶資料\n\n規例下闡明電訊商有責任核對、釐清及核實用戶所提供的資料，然而，建議未有就相關的執行細節及程序作出仔細而詳盡的指引。例如，電訊商該如何，或從何途徑得以核實用戶所提交的個人資料是確切無誤，而非挪取他人資料作登記。顧客買卡後於網上上載個人資料，虛擬網絡供應商亦難以核實資料真偽。建議亦未有清楚指示電訊商該如何應對客戶的個人資料被盜用作登記電話卡等情況。\n\n2. 登記核對系統的設立成本或加重經營困難\n\n本會明白持牌人有責任核實釐清用戶登記資料，然而，設立相關的數據庫和核對系統所需成本所費不貲，附加的成本對於小型電訊商在經營上更是沉重的負擔，而且，規定給予電訊商準備時間倉卒，須於計劃第一階段（即規例生效一百二十天內）建立並預備一個完整的登記系統及數據庫。電訊商為配合規例不得不額外增加營運成本，使經營業務百上加斤。\n\n三、對於創科公司業務發展的影響\n\n1. 新措施或耽誤本地物聯網技術發展\n\n從事物聯網技術開發的創科企業大多使用儲值電話卡作為工具以進行各種軟件研發。此外，電話卡作為合適的媒介經常用於低功率廣域網路測試，為節省時間成本，普遍業界在進行測試期間會同一時間運用大量電話卡。故此，創科企業十分依靠電話卡以進行研發的工作，限制電話卡持有數量或延誤開發技術進程。\n\n2. 電話卡數量限制影響公司業務運作\n\n業界不少為客戶提供數據收集服務的創科公司，會透過短信息服務(SMS)替服務對象建構客戶關係管理系統(CRM)。企業為確保客戶數據的獨立性及準確性，多採用「一客戶一獨立電話卡」的形式。然而，新措施在電話卡數量上的規定，或對管理客戶數據上造成混亂，對公司業務運作上存在一定的困擾。\n\n四、新措施影響廣遠\n\n1. 電話卡應用廣泛，影響觸及跨界別\n\n電話卡的應用層面並不局限於資訊科技業界，建議須慎重思慮對各界別的潛在影響。以運輸及旅遊業界為例，因應工作上的需要，不少的職業司機均持有多部備有「太空卡」的電話裝置，以便與客人溝通聯絡；大型運輸公司的車隊亦植入電話卡作業務上的用途。除此之外，在個人安全層面上，現有不少汽車產品均有內嵌電話卡供使用者於意外發生時可適時撥打求救信號。\n\n五、商會建議\n\n1. 延長諮詢期， 給予各界足夠時間空間準備並了解新措施\n\n本會非常理解打擊濫用電訊服務非法行為的重要性，同時間亦體會各界於尚未有充分且精確的了解下，或對於新措施的實行抱有存疑。再言，新規管下對各界影響廣遠，或需更充分的空間予以討論，充足的時間進行前期安排以配合執行落實的新措施。故本會建議延長諮詢期，讓各界獲更多機會以整改措施。\n\n2. 盼獲豁免或放寬創科企業電話卡數量規管\n\n企業與個人用戶對於電話卡的應用需求不同，創科公司多以電話卡作創新研發之用途。而新規例限企業向每間電訊商申請最多3張電話卡，無疑給予公司在研發創新上的限制，有限的電話卡持有數量亦難免壓抑了企業無限的創新，故本會謹此冀盼當局能豁免或放寬創科企業電話卡數量規管，使本地創科公司在創新路途上順利無阻。\n\n3. 冀能為電訊商提供津貼協助其履行責任\n\n電訊商架設新措施所須求的登記核實系統為謍運上添加額外成本，小型電訊商更難以獨力負擔起新設系統所帶來的沉重成本。故本會冀望當局能為電訊商業界提供補貼或優惠政策，協助電訊商履行其責任。\n\n香港無線科技商會',
    bodyZh: '',
    images: [],
    legacyPath: '/2021/03/simcardregistration/',
    featured: false,
  },
  {
    slug: 'new-term-of-executive-committee-2022-2024',
    kind: 'milestone',
    year: 2022,
    month: '09',
    titleEn: 'New Term of Executive Committee (2022 - 2024)',
    titleZh: '',
    bodyEn: 'Mr. Keith Li was elected as Chairman of Hong Kong Wireless Technology Industry Association in the term of 2022-2024\n\nThe 19th term of Annual General Meeting of Hong Kong Wireless Technology Industry Association (WTIA) was held on 1 September 2022. Mr. Li King Wah (Keith Li), Co-founder and CEO, Innopage Limited was elected to be the Chairman in the term of 2022-2024, with 2 September 2022 as the commencement date.\n\nMr. Li expressed appreciation to WTIA members and members of cabinet for their trust and support, and said he was very honoured to be elected as the Chairman of WTIA in the term of 2022-2024. He stated WTIA will organise various activities to create business opportunities, attract talent for members and the industry.\n\nMr. Li said that he will strive to lead the new Executive Committees and WTIA members to face challenges and difficulties in the new term.\n\nThe following is the list of WTIA committees in 2022-2024:\n\nChairman Mr. Keith Li\n\nVice-Chairman Mr. Donald Chan, Dr. Lawrence Cheung, Mr. Sunny Kok\n\nTreasurer Mr. Nelson Tse\n\nExecutive Committee Mr. Alex Kun, Mr. Antony Ma, Mr. Ivan So (New), Mr. Jimmy Chan, Dr. Lawrence Poon, Mr. Leo To, Ms. Ping Wong, Mr. Vincent Tsui (New)\n\nAbout WTIA\n\nHong Kong Wireless Technology Industry Association (WTIA), established in 2001, is a not-for-profit, politically-neutral trade association dedicated to the wireless and mobile industry.',
    bodyZh: '',
    images: [
      {src: '/images/history/301379874_4923078111125509_7909433195082011540_n-1-768x1024.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2022/09/new-term-of-executive-committee-2022-2024/',
    featured: true,
  },
  {
    slug: 'wtia-21st-anniversary-celebration-and-inauguration-gala-dinner',
    kind: 'milestone',
    year: 2022,
    month: '09',
    titleEn: 'WTIA "20+1st" Anniversary celebration and Inauguration Gala Dinner',
    titleZh: '',
    bodyEn: 'This year marks the 20+1st year of establishment of WTIA.Throughout these years, WTIA keeps on taking the role of a super-connector in the Wireless Communication Industry, to bridge up the gap between government, enterprises, service providers and associations. Bring on the cheer with our 20+1st Anniversary celebration and Inauguration, we are going to organize a Gala Dinner on 29 September 2022.\n\nLook forward to seeing you at the party. *Seats Limited, will be on first come first serve basis\n\nDate: Thursday, 29 September 2022 Time: 7:00pm – 10:00 pm (Registration at 6:45pm) Venue: The Mira Hong Kong (118-130 Nathan Rd, Tsim Sha Tsui) Ticket: $1,750 per seat / $7,000 for half table(4 seats)\n\n*20% off discount for WTIA Platinum Member *10% off discount for WTIA Corporate and Startup Member\n\nRegistration: https://lnkd.in/g4_HjUry\n\nWTIA 香港無線科技商會〈20 + 1 週年慶祝晚宴〉暨新一屆執行委員會就職典禮\n\n為慶賀香港無線科技商會（WTIA） 成立 20 週年， WTIA 將舉辦 20 + 1 週年慶祝晚宴暨新一屆執行委員會就職典禮，在此歡迎各位與我們聚首一堂，歡慶及見證本會跨越二十載的里程碑。\n\n誠邀各位出席，期待慶典當晚見到大家。 *名額有限，報名先到先得\n\n日期：9 月 29 日（星期四） 時間： 晚上 7 時至 10 時 地點：美麗華酒店（尖沙咀彌敦道118-130號）\n\n費用： HKD$ 1,750/ 位 或 HKD$ 7,000/半席（4 位） *白金會員（Platinum）可享 8 折優惠 *企業會員(Corporate)及初創會員(Startup) 可享 9 折優惠\n\n報名：https://form.jotform.com/222562739025456',
    bodyZh: '',
    images: [
      {src: '/images/history/21.jpg', altEn: '', altZh: ''},
      {src: '/images/history/304987776_4955423924557594_1709697925414704627_n-1-770x1024.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2022/09/wtia-21st-anniversary-celebration-and-inauguration-gala-dinner/',
    featured: true,
  },
  {
    slug: 'wtia-20-plus-1st-anniversary-commemorative-book',
    kind: 'milestone',
    year: 2022,
    month: '10',
    titleEn: 'WTIA 20+1st Anniversary Commemorative Book 香港無線科技商會20＋1週年紀念特刊',
    titleZh: '',
    bodyEn: 'WTIA 20+1st Anniversary Commemorative Book is Now Available Online!\n\nThis commemorative book embodies the blessing from our prestigious partners and friendly supporting organisation. Throughout all these years, WTIA is glad and honored to have the support from all corners of the wireless industry, with the unfailing supporting, there was over 100 industrial events has been held last year.\n\nIn the future, WTIA will continue to implement practical works that will help to advance the industry. By working together, we have faith in building a Tech-Friendly ecosystem in Hong Kong.\n\n香港無線科技商會20＋1週年紀念特刊現供閱覽\n\n香港無線科技商會20＋1週年紀念特刊盛載著每位合作夥伴及各方友會送上的美好祝福。多年來，商會在各界鼎力相助下發展蓬勃，單單在過去一年，商會就舉辦了超過100場不同形式的行業活動。\n\n未來，商會將繼續與各界保持緊密合作，共同將香港打造成一個智慧城市。',
    bodyZh: '',
    images: [
      {src: '/images/history/Screenshot-2022-10-11-at-12.21.19-PM-2.png', altEn: '', altZh: ''},
      {src: '/images/history/Screenshot-2022-10-11-at-12.21.19-PM-2.png', altEn: '', altZh: ''}
    ],
    legacyPath: '/2022/10/wtia-201st-anniversary-commemorative-book-%e9%a6%99%e6%b8%af%e7%84%a1%e7%b7%9a%e7%a7%91%e6%8a%80%e5%95%86%e6%9c%8320%ef%bc%8b1%e9%80%b1%e5%b9%b4%e7%b4%80%e5%bf%b5%e7%89%b9%e5%88%8a/',
    featured: false,
  },
  {
    slug: 'tech-connect-ai-leaders-seminar-series',
    kind: 'milestone',
    year: 2025,
    month: '05',
    titleEn: '「Tech Connect 智創互聯」AI 領袖系列研討會 "Tech Connect" AI Leaders Seminar Series',
    titleZh: '',
    bodyEn: 'WTIA 積極推動業界數位轉型，本年度舉行的「Tech Connect 智創互聯」系列活動取得熱烈迴響。其中「人工智能領袖峰會」邀請超過 15 位來自華為、Microsoft、HKPC 等知名企業的技術專家，圍繞「生成式 AI 如何重塑商業模式」展開深度討論，協助本地中小企掌握最新 AI 工具並提升運營效率。\n\nWTIA continues to drive digital transformation within the industry through the highly successful “Tech Connect” event series. The “AI Leaders Summit” featured over 15 tech experts from renowned organizations such as Huawei, Microsoft, and HKPC. The summit focused on how Generative AI is reshaping business models, providing local SMEs with the insights needed to master cutting-edge AI tools and enhance operational efficiency.',
    bodyZh: '',
    images: [
      {src: '/images/history/DSC08503-1-scaled.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2025/05/%e3%80%8ctech-connect-%e6%99%ba%e5%89%b5%e4%ba%92%e8%81%af%e3%80%8dai-%e9%a0%98%e8%a2%96%e7%b3%bb%e5%88%97%e7%a0%94%e8%a8%8e%e6%9c%83-tech-connect-ai-leaders-seminar-series/',
    featured: false,
  },
  {
    slug: '2025-hong-kong-ict-awards-ict-startup-award',
    kind: 'milestone',
    year: 2025,
    month: '10',
    titleEn: '2025 香港資訊及通訊科技獎：資訊科技初創企業獎 2025 Hong Kong ICT Awards: ICT Startup Award',
    titleZh: '',
    bodyEn: '由數字政策辦公室主辦、香港無線科技商會（WTIA）籌辦的「2025 香港資訊及通訊科技獎：資訊科技初創企業獎」圓滿落幕。本屆賽事競爭激烈，旨在發掘具備創新潛力與市場影響力的本地初創。本屆「資訊科技初創企業大獎」由 Entoptica Limited 憑藉其創新技術 SLOPE device 奪得。評審團一致讚揚該項目在醫療科技上的突破及社會貢獻。\n\nSteered by the Digital Policy Office and organized by the Hong Kong Wireless Technology Industry Association (WTIA), the “2025 Hong Kong ICT Awards: ICT Startup Award” has concluded successfully. The awards aim to recognize local startups with exceptional innovation and market potential. This year’s “ICT Startup Grand Award” was presented to Entoptica Limited for their groundbreaking SLOPE device. The jury highly commended the project’s breakthrough in medical technology and its significant social contribution.',
    bodyZh: '',
    images: [
      {src: '/images/history/1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2025/10/2025-%e9%a6%99%e6%b8%af%e8%b3%87%e8%a8%8a%e5%8f%8a%e9%80%9a%e8%a8%8a%e7%a7%91%e6%8a%80%e7%8d%8e%ef%bc%9a%e8%b3%87%e8%a8%8a%e7%a7%91%e6%8a%80%e5%88%9d%e5%89%b5%e4%bc%81%e6%a5%ad%e7%8d%8e/',
    featured: false,
  },
  {
    slug: 'asia-smart-innovation-awards-2025',
    kind: 'milestone',
    year: 2025,
    month: '11',
    titleEn: '2025 亞洲智慧創新大獎 Asia Smart Innovation Awards 2025',
    titleZh: '',
    bodyEn: '「亞洲智慧創新大獎 2025」（前身為亞洲智能應用大獎）於 10 月 16 日在香港康得思酒店舉行頒獎典禮。本屆賽事吸引了來自亞洲 17 個地區的頂尖團隊參與，規模創下歷年之最。本年度最高殊榮「亞洲智能創新大獎」由泰國團隊 RIFFAI 奪得。香港代表亦表現優異，其中 417 Technology Limited 奪得「生活與文化組別」銀獎。\n\nThe “Asia Smart Innovation Awards 2025” (formerly Asia Smart App Awards) held its gala presentation ceremony at Cordis Hong Kong on October 16. Attracting top-tier teams from 17 Asian regions, this year’s scale reached a historic high. The “Asia Smart Innovation Grand Award” was claimed by the Thai team RIFFAI. Hong Kong representatives also delivered outstanding performances, with 417 Technology Limited securing the Silver Award in the “Living & Culture” category.',
    bodyZh: '',
    images: [
      {src: '/images/history/562333706_1252562953570355_3640544314971024985_n-3-1.jpg', altEn: '', altZh: ''}
    ],
    legacyPath: '/2025/11/2025-%e4%ba%9e%e6%b4%b2%e6%99%ba%e6%85%a7%e5%89%b5%e6%96%b0%e5%a4%a7%e7%8d%8e-asia-smart-innovation-awards-2025/',
    featured: false,
  },
]);
