// @vitest-environment node
import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { isolatedAuditDatabase } from "./audit-database-fixture";
import { createInboxRepository } from "@/lib/db/repos/inbox";
import { createMessageEligibilityRepository } from "@/lib/db/repos/message-eligibility";
import { createWoztellInboundEventsRepository, woztellWebhookActor } from "@/lib/db/repos/woztell-inbound-events";
import { sendInboxReply, type InboxReplyDependencies } from "@/lib/admin/inbox-action-core";
import { createDeliveriesRepository, notificationActor } from "@/lib/db/repos/deliveries";
import { dispatchNotification, type NotificationDispatchDependencies } from "@/lib/notifications/dispatch";
import { renderEmail } from "@/lib/email/render";
import { createTestTransport } from "@/lib/email/transport";
import { unsubscribeUrls } from "@/lib/email/unsubscribe-urls";
import { WoztellDeliveryFailure } from "@/lib/channels/woztell";
const staff = { kind: "staff", profileId: "t14d-staff", userId: "t14d-auth" } as const;
const member = { kind: "member", profileId: "t14d-member", userId: "t14d-member-auth" } as const;
let f: Awaited<ReturnType<typeof isolatedAuditDatabase>>;
let inbox: ReturnType<typeof createInboxRepository>, eligibility: ReturnType<typeof createMessageEligibilityRepository>, callbacks: ReturnType<typeof createWoztellInboundEventsRepository>;
const now = () => new Date();
async function seed() {
    await f.pool.query("INSERT INTO profiles(id,auth_user_id,display_name,role,email,consent_marketing,whatsapp_opt_in,whatsapp_number) VALUES('t14d-staff','t14d-auth','Synthetic Staff','staff','staff@example.test',false,false,null),('t14d-member','t14d-member-auth','Synthetic Member','member','member@example.test',true,true,'+85290000000')");
    const id = randomUUID();
    await f.pool.query("INSERT INTO conversations(id,profile_id,channel,handling,last_inbound_at,expires_at) VALUES($1,'t14d-member','whatsapp','human',now(),now()+interval '1 day')", [id]);
    return id;
}
function input(id: string, attempt = randomUUID()) { return { conversationId: id, kind: "session" as const, content: "Synthetic staff reply", templateKey: null, templateVariables: {}, attemptId: attempt }; }
function ports(queue = inbox.queueStaffMessage): InboxReplyDependencies {
    return { inbox: { ...inbox, queueStaffMessage: queue }, eligibility, channel: { sendSessionMessage: vi.fn(async () => ({ status: "sent" as const, providerId: "wamid.synthetic." + randomUUID() })), sendTemplateMessage: vi.fn(async () => ({ status: "sent" as const, providerId: "wamid.synthetic." + randomUUID() })) }, approvedTemplateKeys: () => new Set(), now };
}
async function ledger(id: string) { return (await f.pool.query("SELECT id,delivery_status,error_code,provider_message_id,delivered_at,read_at,send_claim_expires_at FROM messages WHERE conversation_id=$1 AND direction='outbound' ORDER BY created_at,id", [id])).rows; }
describe.skipIf(process.env.RUN_POSTGRES_INTEGRATION !== "1")("staff delivery recovery on actual all-migration PostgreSQL; synthetic provider boundary only", () => {
    beforeAll(async () => { f = await isolatedAuditDatabase(); const load = async () => f.database; inbox = createInboxRepository(load); eligibility = createMessageEligibilityRepository(load); callbacks = createWoztellInboundEventsRepository(now, load); }, 120000);
    beforeEach(async () => { await f.pool.query("TRUNCATE profiles CASCADE"); });
    afterAll(async () => { if (f)
        await f.close(); });
    it("STOP committed after queue but before transport refuses the send and retains a truthful failed ledger", async () => { const id = await seed(), deps = ports(async (a, x) => { const r = await inbox.queueStaffMessage(a, x); await f.pool.query("UPDATE profiles SET whatsapp_opt_in=false WHERE id='t14d-member'; INSERT INTO message_suppressions(profile_id,channel,classification) VALUES('t14d-member','whatsapp','marketing')"); return r; }); await expect(sendInboxReply(staff, input(id), deps)).rejects.toMatchObject({ code: "OPTED_OUT" }); expect(deps.channel.sendSessionMessage).not.toHaveBeenCalled(); const rows = await ledger(id); expect(rows).toHaveLength(1); expect(rows[0].delivery_status).toBe("failed"); expect(rows[0].provider_message_id).toBeNull(); expect(rows[0].send_claim_expires_at).toBeNull(); });
    it("contact STOP after queue is read from the contact store rather than member opt-in", async () => { const id = await seed(), contact = randomUUID(); await f.pool.query("INSERT INTO contacts(id,source,phone_e164,whatsapp_opt_in) VALUES($1,'whatsapp','+85290000001',true)", [contact]); await f.pool.query("UPDATE conversations SET contact_id=$2 WHERE id=$1", [id, contact]); const deps = ports(async (a, x) => { const r = await inbox.queueStaffMessage(a, x); await f.pool.query("UPDATE contacts SET whatsapp_opted_out_at=now() WHERE id=$1", [contact]); return r; }); await expect(sendInboxReply(staff, input(id), deps)).rejects.toMatchObject({ code: "OPTED_OUT" }); expect(deps.channel.sendSessionMessage).not.toHaveBeenCalled(); });
    it("a takeover change after the send claim stops the old human operation", async () => { const id = await seed(), deps = ports(async (a, x) => { const r = await inbox.queueStaffMessage(a, x); await f.pool.query("UPDATE conversations SET handling='bot' WHERE id=$1", [id]); return r; }); await expect(sendInboxReply(staff, input(id), deps)).rejects.toMatchObject({ code: "INVALID_INBOX_HANDLING" }); expect(deps.channel.sendSessionMessage).not.toHaveBeenCalled(); expect((await ledger(id))[0].delivery_status).toBe("failed"); });
    it("a changed recipient link cannot receive an earlier queued reply", async () => { const id = await seed(), contact = randomUUID(); await f.pool.query("INSERT INTO contacts(id,source,phone_e164,whatsapp_opt_in) VALUES($1,'whatsapp','+85290000002',true)", [contact]); const deps = ports(async (a, x) => { const r = await inbox.queueStaffMessage(a, x); await f.pool.query("UPDATE conversations SET contact_id=$2 WHERE id=$1", [id, contact]); return r; }); await expect(sendInboxReply(staff, input(id), deps)).rejects.toMatchObject({ code: "INVALID" }); expect(deps.channel.sendSessionMessage).not.toHaveBeenCalled(); });
    it("unknown acceptance is not retried; a matching synthetic provider echo and delivered/read ticks reconcile the same row", async () => { const id = await seed(), request = input(id), deps = ports(); vi.mocked(deps.channel.sendSessionMessage).mockRejectedValue(new WoztellDeliveryFailure("retryable_network")); await expect(sendInboxReply(staff, request, deps)).rejects.toMatchObject({ code: "DELIVERY_UNCERTAIN" }); await expect(sendInboxReply(staff, request, deps)).rejects.toMatchObject({ code: "DELIVERY_UNCERTAIN" }); expect(deps.channel.sendSessionMessage).toHaveBeenCalledTimes(1); const provider = "wamid.synthetic." + randomUUID(), echo = { recipient: "+85290000000", text: request.content, providerMessageId: provider, origin: "RELAY" as const, sentAt: now() }; expect(await callbacks.recordOutboundEcho(woztellWebhookActor(), echo)).toEqual({ disposition: "adopted" }); expect(await callbacks.recordOutboundEcho(woztellWebhookActor(), echo)).toEqual({ disposition: "duplicate" }); let rows = await ledger(id); expect(rows).toHaveLength(1); expect(rows[0].delivery_status).toBe("sent"); expect(rows[0].delivered_at).toBeNull(); const tick = { providerMessageId: provider, status: "delivered" as const, errorCode: null, occurredAt: now() }; expect((await callbacks.recordDeliveryStatus(woztellWebhookActor(), tick)).matched).toBe(true); await callbacks.recordDeliveryStatus(woztellWebhookActor(), { ...tick, status: "read" }); await callbacks.recordDeliveryStatus(woztellWebhookActor(), { ...tick, status: "sent" }); rows = await ledger(id); expect(rows[0].delivery_status).toBe("read"); expect(rows[0].delivered_at).not.toBeNull(); expect(rows[0].read_at).not.toBeNull(); await expect(sendInboxReply(staff, request, deps)).resolves.toMatchObject({ status: "already_sent" }); expect(deps.channel.sendSessionMessage).toHaveBeenCalledTimes(1); expect(Number((await f.pool.query("SELECT count(*) AS n FROM audit_events WHERE target_id=$1 AND action='conversation.reply.queued'", [id])).rows[0].n)).toBe(1); });
    it("a new client attempt cannot bypass an unresolved identical send", async () => { const id = await seed(), deps = ports(); vi.mocked(deps.channel.sendSessionMessage).mockRejectedValue(new WoztellDeliveryFailure("retryable_network")); await expect(sendInboxReply(staff, input(id), deps)).rejects.toMatchObject({ code: "DELIVERY_UNCERTAIN" }); await expect(sendInboxReply(staff, input(id), deps)).rejects.toMatchObject({ code: "DELIVERY_UNCERTAIN" }); expect(deps.channel.sendSessionMessage).toHaveBeenCalledTimes(1); expect(await ledger(id)).toHaveLength(1); });
    it("an ambiguous identical echo never selects one of two queued attempts by recency", async () => { const id = await seed(), { outboundKeyFor } = await import("@/lib/admin/inbox-action-core"); const r = input(id); await inbox.queueStaffMessage(staff, { conversationId: id, kind: r.kind, content: r.content, templateKey: null, templateVariables: {}, outboundKey: outboundKeyFor(r) }); /* Historical ambiguity fixture: the repaired queue now refuses a second unresolved identical attempt. */ /* Historical ambiguity fixture: the repaired queue now refuses a second unresolved identical attempt. */ await f.pool.query("INSERT INTO messages(conversation_id,role,channel,direction,content,delivery_status,sent_by_profile_id,outbound_key,send_claim_expires_at) VALUES($1,'staff','whatsapp','outbound',$2,'queued',$3,$4,now()+interval '2 minutes')", [id, r.content, staff.profileId, outboundKeyFor(input(id))]); expect(await callbacks.recordOutboundEcho(woztellWebhookActor(), { recipient: "+85290000000", text: "Synthetic staff reply", providerMessageId: "wamid.synthetic." + randomUUID(), origin: "RELAY", sentAt: now() })).toEqual({ disposition: "inserted" }); const rows = await ledger(id); expect(rows.filter(r => r.delivery_status === "queued" && r.provider_message_id === null)).toHaveLength(2); expect(rows).toHaveLength(3); });
    it("wrong-locale approved template is refused before the queue or provider", async () => { const id = await seed(), deps = { ...ports(), approvedTemplateKeys: () => new Set(["concierge_follow_up_en"] as const) }; await f.pool.query("UPDATE conversations SET locale='zh-HK' WHERE id=$1", [id]); await expect(sendInboxReply(staff, { ...input(id), kind: "template", templateKey: "concierge_follow_up_en", templateVariables: { memberName: "Synthetic", supportUrl: "https://preview.example.test/contact" } }, deps)).rejects.toMatchObject({ code: "INVALID" }); expect(deps.channel.sendTemplateMessage).not.toHaveBeenCalled(); expect(await ledger(id)).toHaveLength(0); });
    it("template approval withdrawn during queue is rechecked before effects", async () => { const id = await seed(); let reads = 0; const deps = { ...ports(), approvedTemplateKeys: () => ++reads === 1 ? new Set(["concierge_follow_up_en"] as const) : new Set<never>() }; await expect(sendInboxReply(staff, { ...input(id), kind: "template", templateKey: "concierge_follow_up_en", templateVariables: { memberName: "Synthetic", supportUrl: "https://preview.example.test/contact" } }, deps)).rejects.toMatchObject({ code: "TEMPLATE_NOT_APPROVED" }); expect(deps.channel.sendTemplateMessage).not.toHaveBeenCalled(); expect((await ledger(id))[0].error_code).toBe("pre_send_blocked"); });
    it("a provider-declared refusal can retry the same effect and same SQL row", async () => { const id = await seed(), request = input(id), deps = ports(); vi.mocked(deps.channel.sendSessionMessage).mockRejectedValueOnce(new WoztellDeliveryFailure("provider_client_error")); await expect(sendInboxReply(staff, request, deps)).rejects.toMatchObject({ code: "DELIVERY_FAILED" }); await expect(sendInboxReply(staff, request, deps)).resolves.toMatchObject({ status: "sent" }); expect(deps.channel.sendSessionMessage).toHaveBeenCalledTimes(2); expect(await ledger(id)).toHaveLength(1); });
    it("worker crash with an expired queued lease remains uncertain and never inherits a send", async () => { const id = await seed(), request = input(id), deps = ports(); const { outboundKeyFor } = await import("@/lib/admin/inbox-action-core"); await inbox.queueStaffMessage(staff, { conversationId: id, kind: request.kind, content: request.content, templateKey: null, templateVariables: {}, outboundKey: outboundKeyFor(request) }); await f.pool.query("UPDATE messages SET send_claim_expires_at=now()-interval '1 hour' WHERE conversation_id=$1", [id]); await expect(sendInboxReply(staff, request, deps)).rejects.toMatchObject({ code: "DELIVERY_UNCERTAIN" }); expect(deps.channel.sendSessionMessage).not.toHaveBeenCalled(); expect((await ledger(id))[0].delivery_status).toBe("queued"); });
    it("later legitimate identical replies have distinct attempts while same-attempt replay sends once", async () => { const id = await seed(), one = input(id), deps = ports(); await sendInboxReply(staff, one, deps); await sendInboxReply(staff, one, deps); await sendInboxReply(staff, input(id), deps); expect(deps.channel.sendSessionMessage).toHaveBeenCalledTimes(2); expect(await ledger(id)).toHaveLength(2); });
    it("campaign timeout is an unknown effect and does not retry the same persisted delivery", async () => { await seed(); const contact = randomUUID(); await f.pool.query("INSERT INTO contacts(id,source,phone_e164,whatsapp_opt_in) VALUES($1,'whatsapp','+85290000003',true)", [contact]); const deliveries = createDeliveriesRepository(async () => f.database), send = vi.fn(async () => { throw new WoztellDeliveryFailure("retryable_network"); }), deps: NotificationDispatchDependencies = { eligibility, deliveries, templates: { approved: async () => ({ keys: new Set(["wtia_announcement_en"]), empty: false }) }, whatsappTransport: { sendTemplateMessage: send }, emailTransport: createTestTransport(), renderEmail, unsubscribeUrls, emailFrom: "Synthetic <test@example.test>" }; const request = { recipient: { kind: "contact" as const, contactId: contact }, channel: "whatsapp" as const, template: "wtia_announcement_en" as const, variables: { memberName: "Synthetic", headline: "Synthetic Notice", detailUrl: "https://preview.example.test/news" }, idempotencyKey: "notify:t14d:" + randomUUID() }; expect(await dispatchNotification(notificationActor("campaign"), request, deps)).toMatchObject({ status: "failed" }); expect(await dispatchNotification(notificationActor("campaign"), request, deps)).toMatchObject({ status: "failed" }); expect(send).toHaveBeenCalledTimes(1); const rows = await f.pool.query("SELECT status,error_code,attempt_count FROM whatsapp_log WHERE idempotency_key=$1", [request.idempotencyKey]); expect(rows.rows).toEqual([{ status: "failed", error_code: "provider_acceptance_uncertain", attempt_count: 1 }]); });
    it("campaign STOP committed during reservation blocks dispatch using fresh actual contact facts", async () => { await seed(); const contact = randomUUID(); await f.pool.query("INSERT INTO contacts(id,source,phone_e164,whatsapp_opt_in) VALUES($1,'whatsapp','+85290000003',true)", [contact]); const deliveries = createDeliveriesRepository(async () => f.database), send = vi.fn(async () => ({ status: "sent" as const, providerId: "wamid.synthetic" })), deps: NotificationDispatchDependencies = { eligibility, deliveries: { ...deliveries, reserveWhatsapp: async (a, x) => { const r = await deliveries.reserveWhatsapp(a, x); await f.pool.query("UPDATE contacts SET whatsapp_opted_out_at=now() WHERE id=$1", [contact]); return r; } }, templates: { approved: async () => ({ keys: new Set(["wtia_announcement_en"]), empty: false }) }, whatsappTransport: { sendTemplateMessage: send }, emailTransport: createTestTransport(), renderEmail, unsubscribeUrls, emailFrom: "Synthetic <test@example.test>" }; const request = { recipient: { kind: "contact" as const, contactId: contact }, channel: "whatsapp" as const, template: "wtia_announcement_en" as const, variables: { memberName: "Synthetic", headline: "Synthetic Notice", detailUrl: "https://preview.example.test/news" }, idempotencyKey: "notify:t14d:" + randomUUID() }; expect(await dispatchNotification(notificationActor("campaign"), request, deps)).toEqual({ status: "skipped", reason: "suppressed" }); expect(send).not.toHaveBeenCalled(); expect((await f.pool.query("SELECT status,provider_id FROM whatsapp_log WHERE idempotency_key=$1", [request.idempotencyKey])).rows).toEqual([{ status: "failed", provider_id: null }]); });
    it("member actor cannot queue/reply or manufacture provider callbacks", async () => { const id = await seed(), deps = ports(); await expect(sendInboxReply(member, input(id), deps)).rejects.toThrow("FORBIDDEN"); await expect(callbacks.recordDeliveryStatus(member, { providerMessageId: "synthetic", status: "delivered", errorCode: null, occurredAt: now() })).rejects.toThrow("FORBIDDEN"); expect(await ledger(id)).toHaveLength(0); });
});
