// @vitest-environment node
import {randomUUID,randomBytes} from 'node:crypto';
import Stripe from 'stripe';
import {afterAll,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {isolatedAuditDatabase} from './audit-database-fixture';
const state=vi.hoisted(()=>({database:null as Awaited<ReturnType<typeof isolatedAuditDatabase>>['database']|null}));
vi.mock('@/lib/db/repos/common',async original=>({...await original<typeof import('@/lib/db/repos/common')>(),getDb:async()=>{if(!state.database)throw Error('ISOLATED_DATABASE_NOT_READY');return state.database;}}));
import {eventOrdersRepository} from '@/lib/db/repos/event-orders';
import {ANONYMOUS_ACTOR} from '@/lib/membership/lifecycle';
import {systemActor} from '@/lib/auth/authorize';
import {processStripeEvent} from '@/lib/billing/webhook-service';
import {createTicketProcessor} from '@/lib/billing/ticket-webhook-processor';
import {createWebhookPost} from '@/lib/api/stripe-webhook-route';
import {renderEmail} from '@/lib/email/render';
import {createTestTransport} from '@/lib/email/transport';
import {RefundPendingError} from '@/lib/billing/stripe';
const now=new Date('2030-01-01T00:00:00Z'),actor=systemActor('stripe-webhook');
let f:Awaited<ReturnType<typeof isolatedAuditDatabase>>;
async function purchase(capacity=2){
 const eventId=randomUUID();await f.pool.query("INSERT INTO events(id,slug,title_en,title_zh,description_en,starts_at,published,status,registration_mode,ticket_price_hkd_cents,capacity,visibility) VALUES($1,$2,'Synthetic T14C event','合成T14C活動','Synthetic only','2031-12-31',true,'published','ticketed',1000,$3,'public')",[eventId,'synthetic-t14c-'+eventId,capacity]);
 const input={actor:ANONYMOUS_ACTOR,eventId,buyerProfileId:null,buyerName:'Synthetic Buyer',buyerEmail:'buyer@example.test',buyerLocale:'en' as const,idempotencyKey:randomUUID(),seats:[{name:'Synthetic Attendee',email:'attendee@example.test'}],amountHkdCents:1000,now};
 const created=await eventOrdersRepository.createOrder(input);if(!created.ok)throw Error('FIXTURE_ORDER_MISSING');const session='cs_test_synthetic_'+randomUUID();expect(await eventOrdersRepository.attachSession(created.order.id,session,'https://checkout.stripe.com/test')).toBe(true);return {input,eventId,orderId:created.order.id,session};
}
function ports(){const notices=vi.fn(async()=>{}),refund=vi.fn(async()=>{throw new RefundPendingError();}),reconciled=vi.fn(async()=>false);return{notices,refund,reconciled,processor:createTicketProcessor({orders:eventOrdersRepository,fullyRefundedPaymentIntent:reconciled,refundPaymentIntent:refund,email:{renderEmail,transport:createTestTransport(),emailFrom:'Synthetic <test@example.test>'},appUrl:'https://preview.example.test',passSecret:'synthetic-isolated-t14c-pass-secret-32',now:()=>now,deliverQueuedOrderNotices:notices})};}
function event(x:Awaited<ReturnType<typeof purchase>>,override:Record<string,unknown>={},type='checkout.session.completed'):Stripe.Event{return {id:'evt_test_synthetic_'+randomUUID(),object:'event',type,created:now.getTime()/1000,livemode:false,data:{object:{id:x.session,object:'checkout.session',metadata:{kind:'event_ticket',orderId:x.orderId},client_reference_id:x.orderId,payment_intent:'pi_test_synthetic',payment_status:'paid',amount_total:1000,currency:'hkd',...override}}} as unknown as Stripe.Event;}
async function untouched(x:Awaited<ReturnType<typeof purchase>>){expect((await f.pool.query('SELECT status,paid_at,refunded_at FROM event_orders WHERE id=$1',[x.orderId])).rows[0]).toEqual({status:'pending',paid_at:null,refunded_at:null});expect(Number((await f.pool.query("SELECT count(*) AS n FROM audit_events WHERE target_id=$1 AND action<>'event.order.created'",[x.orderId])).rows[0].n)).toBe(0);expect(Number((await f.pool.query('SELECT count(*) AS n FROM ticket_email_outbox WHERE order_id=$1',[x.orderId])).rows[0].n)).toBe(0);}
describe.skipIf(process.env.RUN_POSTGRES_INTEGRATION!=='1')('event payment authority and recovery on actual all-migration PostgreSQL',()=>{
 beforeAll(async()=>{f=await isolatedAuditDatabase();state.database=f.database;},120000);beforeEach(async()=>{await f.pool.query('TRUNCATE events CASCADE');});afterAll(async()=>{state.database=null;if(f)await f.close();});
 it('the last seat has one held allocation under concurrent real transactions',async()=>{const x=await purchase(1);await eventOrdersRepository.expireBySession(x.session,x.orderId);const results=await Promise.all([eventOrdersRepository.createOrder({...x.input,idempotencyKey:randomUUID()}),eventOrdersRepository.createOrder({...x.input,idempotencyKey:randomUUID()})]);expect(results.filter(r=>r.ok)).toHaveLength(1);expect(results.filter(r=>!r.ok)).toEqual([{ok:false,reason:'SOLD_OUT'}]);expect(Number((await f.pool.query("SELECT count(*) AS n FROM event_orders WHERE event_id=$1 AND status='pending'",[x.eventId])).rows[0].n)).toBe(1);});
 it.each([{amount_total:999},{amount_total:1001},{currency:'usd'},{amount_total:null}])('rejects a paid provider receipt %j without changing the order, audit or durable notices',async override=>{const x=await purchase(),p=ports();await expect(processStripeEvent(event(x,override),actor,undefined,p.processor)).rejects.toMatchObject({code:'INVALID_WEBHOOK_EVENT'});await untouched(x);expect(p.notices).not.toHaveBeenCalled();expect(p.refund).not.toHaveBeenCalled();});
 it('rejects a provider session belonging to a different correlated order',async()=>{const x=await purchase(),other=randomUUID(),p=ports();await expect(processStripeEvent(event(x,{metadata:{kind:'event_ticket',orderId:other},client_reference_id:other}),actor,undefined,p.processor)).rejects.toMatchObject({code:'INVALID_WEBHOOK_EVENT'});await untouched(x);expect(p.notices).not.toHaveBeenCalled();});
 it('rejects expiry with a mismatched provider order reference without releasing the correct hold',async()=>{const x=await purchase(),other=randomUUID(),p=ports();await expect(processStripeEvent(event(x,{metadata:{kind:'event_ticket',orderId:other},client_reference_id:other},'checkout.session.expired'),actor,undefined,p.processor)).rejects.toMatchObject({code:'INVALID_WEBHOOK_EVENT'});await untouched(x);});
 it('delayed unpaid completion cannot allocate a ticket; paid completion replay and older expiry keep one paid audit and one durable notice per kind',async()=>{const x=await purchase(),p=ports();await expect(processStripeEvent(event(x,{payment_status:'unpaid'}),actor,undefined,p.processor)).rejects.toMatchObject({code:'INVALID_WEBHOOK_EVENT'});await untouched(x);const paid=event(x,{},'checkout.session.async_payment_succeeded');await processStripeEvent(paid,actor,undefined,p.processor);await processStripeEvent(paid,actor,undefined,p.processor);await processStripeEvent(event(x,{},'checkout.session.expired'),actor,undefined,p.processor);expect((await eventOrdersRepository.orderById(x.orderId))?.status).toBe('paid');expect(Number((await f.pool.query("SELECT count(*) AS n FROM audit_events WHERE target_id=$1 AND action='event.order.paid'",[x.orderId])).rows[0].n)).toBe(1);expect((await f.pool.query('SELECT kind,count(*)::int AS n FROM ticket_email_outbox WHERE order_id=$1 GROUP BY kind ORDER BY kind',[x.orderId])).rows).toEqual([{kind:'confirmation',n:1},{kind:'pass',n:1}]);});
 it('late payment after explicit expiry remains refund_pending until an actual successful reconciliation; no pass or refunded toast evidence is manufactured',async()=>{const x=await purchase(),p=ports();await eventOrdersRepository.expireBySession(x.session,x.orderId);await processStripeEvent(event(x),actor,undefined,p.processor);expect((await f.pool.query('SELECT status,refunded_at FROM event_orders WHERE id=$1',[x.orderId])).rows[0]).toEqual({status:'refund_pending',refunded_at:null});expect((await f.pool.query('SELECT kind FROM ticket_email_outbox WHERE order_id=$1',[x.orderId])).rows).toEqual([{kind:'refund'}]);expect(p.notices).not.toHaveBeenCalled();expect(p.refund).toHaveBeenCalledTimes(1);});
 it('a real audit insertion fault rolls settlement/notices back; retry commits once',async()=>{const x=await purchase(),p=ports();await f.pool.query("CREATE FUNCTION t14c_fail_paid_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='event.order.paid' THEN RAISE EXCEPTION 'synthetic settlement audit fault'; END IF; RETURN NEW; END $$; CREATE TRIGGER t14c_paid_audit_fault BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION t14c_fail_paid_audit()");try{await expect(processStripeEvent(event(x),actor,undefined,p.processor)).rejects.toMatchObject({cause:expect.objectContaining({message:'synthetic settlement audit fault',code:'P0001'})});await untouched(x);}finally{await f.pool.query('DROP TRIGGER t14c_paid_audit_fault ON audit_events; DROP FUNCTION t14c_fail_paid_audit()');}await processStripeEvent(event(x),actor,undefined,p.processor);expect((await eventOrdersRepository.orderById(x.orderId))?.status).toBe('paid');});
 it('real Stripe SDK signature verification rejects a tampered body before any repository write',async()=>{const x=await purchase(),p=ports(),secret='whsec_'+randomBytes(32).toString('hex'),stripe=new Stripe('sk_test_synthetic_not_a_provider_credential');const body=JSON.stringify(event(x)),signature=stripe.webhooks.generateTestHeaderString({payload:body,secret});const post=createWebhookPost({constructEvent:(body,signature)=>stripe.webhooks.constructEvent(body,signature,secret),processEvent:e=>processStripeEvent(e,actor,undefined,p.processor)});const response=await post(new Request('https://preview.example.test/api/stripe/webhook',{method:'POST',headers:{'stripe-signature':signature},body:body+' '}));expect(response.status).toBe(400);expect(await response.json()).toEqual({error:'INVALID_SIGNATURE'});await untouched(x);});
});
