"use server";
import {requireAdminActor} from "@/lib/auth/actor";
import {isAuthorizationDenial} from "@/lib/auth/authorization-denial";
import {knowledgeGovernanceRepository,knowledgeManagementEnabled,knowledgeVersionSchema,knowledgeReviewSchema,knowledgeIndexSchema} from "@/lib/db/repos/knowledge-governance";
type Result=Readonly<{status:"saved"|"invalid"|"unavailable"|"forbidden"|"disabled"|"reconcile"|"configuration"}>;
function failure(error:unknown):Result {if(isAuthorizationDenial(error))return {status:"forbidden"};if(error instanceof Error){if(error.message==="KNOWLEDGE_APPROVER_NOT_ALLOWED"||error.message==="KNOWLEDGE_SELF_APPROVAL_FORBIDDEN")return {status:"forbidden"};if(error.message==="KNOWLEDGE_APPROVER_CONFIGURATION_REQUIRED"||error.message==="OPENAI_API_KEY_REQUIRED"||error.message==="KNOWLEDGE_PROVIDER_CONFIG_REQUIRED")return {status:"configuration"};if(/^KNOWLEDGE_INDEX_(RECONCILIATION_REQUIRED|STALE)$/.test(error.message))return {status:"reconcile"};if(error.message==="KB_CONTENT_TOO_FRAGMENTED")return {status:"invalid"};if(/^KNOWLEDGE_(VERSION_CONFLICT|SOURCE_CONFLICT|EFFECTIVE_ORDER_INVALID|LOCALE_CONFLICT|REVIEW_CONFLICT|VERSION_MISSING)$/.test(error.message))return {status:"invalid"};}return {status:"unavailable"};}
export async function createKnowledgeVersionAction(input:unknown):Promise<Result>{try{const actor=await requireAdminActor();if(!knowledgeManagementEnabled())return {status:"disabled"};const parsed=knowledgeVersionSchema.safeParse(input);if(!parsed.success)return {status:"invalid"};await knowledgeGovernanceRepository.createVersion(actor,parsed.data);return {status:"saved"};}catch(error){return failure(error);}}
export async function reviewKnowledgeVersionAction(input:unknown):Promise<Result>{try{const actor=await requireAdminActor();if(!knowledgeManagementEnabled())return {status:"disabled"};const parsed=knowledgeReviewSchema.safeParse(input);if(!parsed.success)return {status:"invalid"};await knowledgeGovernanceRepository.reviewVersion(actor,parsed.data);return {status:"saved"};}catch(error){return failure(error);}}
export async function indexKnowledgeVersionAction(input:unknown):Promise<Result>{try{const actor=await requireAdminActor();if(!knowledgeManagementEnabled())return {status:"disabled"};const parsed=knowledgeIndexSchema.safeParse(input);if(!parsed.success)return {status:"invalid"};await knowledgeGovernanceRepository.indexVersion(actor,parsed.data);return {status:"saved"};}catch(error){return failure(error);}}
