"use client";
import {useEffect,useState,useTransition,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {useAdminUnsavedChanges} from "@/components/admin/unsaved-changes-guard";
import {createKnowledgeVersionAction,reviewKnowledgeVersionAction,indexKnowledgeVersionAction} from "@/lib/admin/knowledge-actions";
import type {KnowledgeVersionSummary} from "@/lib/db/repos/knowledge-governance";
export type KnowledgeLabels=Readonly<Record<"heading"|"description"|"create"|"source"|"newSource"|"title"|"url"|"body"|"locale"|"audience"|"public"|"staff"|"effectiveFrom"|"effectiveTo"|"reviewDue"|"facts"|"factsHelp"|"save"|"version"|"owner"|"approver"|"supersedes"|"indexState"|"approvalState"|"contentHash"|"reviewSource"|"approve"|"withdraw"|"index"|"empty"|"noValue"|"saved"|"invalid"|"unavailable"|"forbidden"|"disabled"|"reconcile"|"configuration"|"pending"|"en"|"zh-HK"|"unverified"|"draft"|"approved"|"withdrawn"|"unindexed"|"indexing"|"ready"|"failed"|"previous"|"next",string>>;
const field="rounded-md border border-input bg-background px-3 py-2 text-foreground";
export function KnowledgeWorkspace({labels,versions,sourceId,enabled,locale}:Readonly<{labels:KnowledgeLabels;versions:readonly KnowledgeVersionSummary[];sourceId:string;enabled:boolean;locale:"en"|"zh-HK"}>){
 const [target,setTarget]=useState("");const [status,setStatus]=useState<Awaited<ReturnType<typeof createKnowledgeVersionAction>>["status"]|null>(null);const [pending,startTransition]=useTransition();const router=useRouter();const {setDirty,confirmLeave}=useAdminUnsavedChanges();
 useEffect(()=>()=>setDirty(false),[setDirty]);
 const selected=versions.find(row=>`${row.sourceId}:${row.locale}:${row.version}`===target);const latest=[...new Map(versions.map(row=>[`${row.sourceId}:${row.locale}`,versions.filter(candidate=>candidate.sourceId===row.sourceId&&candidate.locale===row.locale).sort((a,b)=>b.version-a.version)[0]!])).values()];
 const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Hong_Kong",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value)):"";
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);let input:unknown;try{const asDate=(name:string)=>new Date(String(data.get(name))+"T00:00:00+08:00").toISOString();const nextLocale=String(data.get("locale"));const identity=selected?.sourceId??sourceId;const prior=versions.filter(row=>row.sourceId===identity&&row.locale===nextLocale).sort((a,b)=>b.version-a.version)[0];input={sourceId:identity,expectedVersion:prior?.version??0,namespace:"m4a-core-v1",title:String(data.get("title")),url:String(data.get("url")),content:String(data.get("content")),locale:nextLocale,audience:String(data.get("audience")),effectiveFrom:asDate("effectiveFrom"),effectiveTo:data.get("effectiveTo")?asDate("effectiveTo"):null,reviewDue:asDate("reviewDue"),structuredFacts:JSON.parse(String(data.get("facts")??"{}"))};}catch{setStatus("invalid");return;}setStatus(null);startTransition(async()=>{try{const result=await createKnowledgeVersionAction(input);setStatus(result.status);if(result.status==="saved"){setDirty(false);router.refresh();}}catch{setStatus("unavailable");}});}
 function mutate(row:KnowledgeVersionSummary,operation:"approve"|"withdraw"|"index"){setStatus(null);startTransition(async()=>{try{const input={sourceId:row.sourceId,locale:row.locale,version:row.version};const result=operation==="index"?await indexKnowledgeVersionAction(input):await reviewKnowledgeVersionAction({...input,decision:operation});setStatus(result.status);if(result.status==="saved")router.refresh();}catch{setStatus("unavailable");}});}
 return <div className="grid gap-6 min-w-0"><p className="text-sm text-muted-foreground">{labels.description}</p>{!enabled?<p role="status">{labels.disabled}</p>:null}
 <details className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">{labels.create}</summary>
 <label className="mt-4 grid gap-2 text-sm">{labels.source}<select className={field} value={target} onChange={event=>{if(confirmLeave()){setTarget(event.target.value);setDirty(false);}}}><option value="">{labels.newSource}</option>{latest.map(row=><option key={`${row.sourceId}:${row.locale}`} value={`${row.sourceId}:${row.locale}:${row.version}`}>{row.title} · {labels[row.locale]} · {labels.version} {row.version}</option>)}</select></label>
 <form key={target} aria-label={labels.create} onSubmit={submit} onChange={()=>setDirty(true)} className="mt-4 grid gap-4 sm:grid-cols-2">
 {(["title","url"] as const).map(name=><label key={name} className="grid gap-2 text-sm">{labels[name]}<input name={name} defaultValue={selected?.[name]??""} type={name==="url"?"url":"text"} maxLength={name==="title"?300:2000} required className={field}/></label>)}
 <label className="grid gap-2 text-sm">{labels.locale}<select name="locale" defaultValue={selected?.locale??locale} className={field}><option value="en">{labels.en}</option><option value="zh-HK">{labels["zh-HK"]}</option></select></label>
 <label className="grid gap-2 text-sm">{labels.audience}<select name="audience" defaultValue={selected?.audience??"staff"} className={field}><option value="staff">{labels.staff}</option><option value="public">{labels.public}</option></select></label>
 {(["effectiveFrom","effectiveTo","reviewDue"] as const).map(name=><label key={name} className="grid gap-2 text-sm">{labels[name]}<input name={name} type="date" defaultValue={date(selected?.[name]??null)} required={name!=="effectiveTo"} className={field}/></label>)}
 <label className="grid gap-2 text-sm sm:col-span-2">{labels.body}<textarea name="content" defaultValue={selected?.originalContent??""} maxLength={100000} required rows={8} className={field}/></label>
 <label className="grid gap-2 text-sm sm:col-span-2">{labels.facts}<textarea name="facts" defaultValue={JSON.stringify(selected?.structuredFacts??{},null,2)} rows={3} aria-describedby="knowledge-facts-help" className={field}/><span id="knowledge-facts-help" className="text-muted-foreground">{labels.factsHelp}</span></label>
 <button disabled={pending||!enabled} type="submit" className="rounded-md bg-primary px-4 py-2 text-primary-foreground sm:col-span-2">{pending?labels.pending:labels.save}</button>
 </form></details>
 {status?<p role="status" aria-live="polite">{labels[status]}</p>:null}
 {!versions.length?<p>{labels.empty}</p>:versions.map(row=><article key={`${row.sourceId}:${row.locale}:${row.version}`} className="min-w-0 rounded-2xl border border-border p-5">
 <h2 className="text-lg font-semibold break-words">{row.title} · {labels[row.locale]} · {labels.version} {row.version}</h2>
 <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">{(["audience","owner","approver","effectiveFrom","effectiveTo","reviewDue","supersedes","approvalState","indexState","contentHash"] as const).map(name=>{const value=name==="owner"?row.ownerId:name==="approver"?row.approverId:name==="supersedes"?row.supersedesVersion:row[name];const displayed=(name==="audience"||name==="approvalState"||name==="indexState")&&typeof value==="string"&&value in labels?labels[value as keyof KnowledgeLabels]:value;return <div key={name}><dt className="text-muted-foreground">{labels[name]}</dt><dd className="break-all">{displayed??labels.noValue}</dd></div>;})}</dl>
 <details className="mt-4"><summary className="cursor-pointer font-medium">{labels.reviewSource}</summary><a href={row.url} target="_blank" rel="noopener noreferrer" className="mt-3 block break-all underline">{row.url}</a><pre className="my-4 whitespace-pre-wrap break-words text-sm">{row.originalContent??labels.noValue}</pre><dl>{Object.entries(row.structuredFacts).map(([key,value])=><div key={key} className="my-2"><dt className="font-medium">{key}</dt><dd className="break-words">{String(value)}</dd></div>)}</dl></details>
 <div className="mt-4 flex flex-wrap gap-3">{row.approvalState==="draft"?<button disabled={pending||!enabled} onClick={()=>mutate(row,"approve")} className="rounded-md border border-border px-3 py-2">{labels.approve}</button>:null}{row.approvalState==="approved"&&row.indexState==="unindexed"?<button disabled={pending||!enabled} onClick={()=>mutate(row,"index")} className="rounded-md border border-border px-3 py-2">{labels.index}</button>:null}{row.approvalState==="approved"?<button disabled={pending||!enabled} onClick={()=>mutate(row,"withdraw")} className="rounded-md border border-border px-3 py-2">{labels.withdraw}</button>:null}</div>
 </article>)}
 </div>;
}
