import type {Member360} from "@/lib/admin/member-360";

export type Member360Labels = Readonly<{
  profile: string; companies: string; membership: string; engagement: string; emails: string; events: string; notes: string;
  empty: string; name: string; email: string; phone: string; role: string; plan: string; status: string; renewal: string; score: string; trend: string;
  company: string; companyRole: string; event: string; occurredAt: string; subject: string; emailStatus: string; noteAuthor: string; noteCreatedAt: string;
  stripeCustomer: string; stripeSubscription: string;
}>;

export function Member360View({view, labels, stripeCustomerHref, stripeSubscriptionHref}: {view: Member360; labels: Member360Labels; stripeCustomerHref: string | null; stripeSubscriptionHref: string | null}) {
  const field = (label: string, value: string | number | null) => <dt className="text-sm text-muted-foreground">{label}<dd className="mt-1 text-foreground">{value ?? labels.empty}</dd></dt>;
  return <div className="grid gap-6 lg:grid-cols-2">
    <section className="glass-card space-y-4 p-5 sm:p-8" aria-labelledby="member-profile-heading"><h2 className="font-serif text-2xl font-semibold" id="member-profile-heading">{labels.profile}</h2><dl className="grid gap-4 sm:grid-cols-2">{field(labels.name, view.profile.displayName)}{field(labels.email, view.profile.email)}{field(labels.phone, view.profile.phone)}{field(labels.role, view.profile.role)}</dl></section>
    <section className="glass-card space-y-4 p-5 sm:p-8" aria-labelledby="member-companies-heading"><h2 className="font-serif text-2xl font-semibold" id="member-companies-heading">{labels.companies}</h2>{view.companies.length === 0 ? <p className="text-sm text-muted-foreground">{labels.empty}</p> : <ul className="space-y-3">{view.companies.map((company) => <li className="flex justify-between gap-4 border-b border-border pb-3 last:border-0 last:pb-0" key={company.id}><span>{company.name}</span><span className="text-sm text-muted-foreground">{company.role}</span></li>)}</ul>}</section>
    <section className="glass-card space-y-4 p-5 sm:p-8" aria-labelledby="member-membership-heading"><h2 className="font-serif text-2xl font-semibold" id="member-membership-heading">{labels.membership}</h2>{view.membership ? <dl className="grid gap-4 sm:grid-cols-2">{field(labels.plan, view.membership.planCode)}{field(labels.status, view.membership.status)}{field(labels.renewal, view.membership.renewalAt)}<dt className="text-sm text-muted-foreground">{labels.stripeCustomer}<dd className="mt-1 text-foreground">{stripeCustomerHref ? <a className="text-primary underline-offset-4 hover:underline" href={stripeCustomerHref} rel="noreferrer" target="_blank">{view.membership.stripeCustomerId}</a> : labels.empty}</dd></dt><dt className="text-sm text-muted-foreground">{labels.stripeSubscription}<dd className="mt-1 text-foreground">{stripeSubscriptionHref ? <a className="text-primary underline-offset-4 hover:underline" href={stripeSubscriptionHref} rel="noreferrer" target="_blank">{view.membership.stripeSubscriptionId}</a> : labels.empty}</dd></dt></dl> : <p className="text-sm text-muted-foreground">{labels.empty}</p>}</section>
    <section className="glass-card space-y-4 p-5 sm:p-8" aria-labelledby="member-engagement-heading"><h2 className="font-serif text-2xl font-semibold" id="member-engagement-heading">{labels.engagement}</h2><dl className="grid gap-4 sm:grid-cols-2">{field(labels.score, view.engagement.score)}{field(labels.trend, view.engagement.trend)}</dl>{view.engagement.events.length === 0 ? <p className="text-sm text-muted-foreground">{labels.empty}</p> : <ul className="space-y-3">{view.engagement.events.map((event) => <li className="border-t border-border pt-3" key={event.id}><p>{event.type} · {event.points}</p><p className="text-sm text-muted-foreground">{event.occurredAt}</p></li>)}</ul>}</section>
    <section className="glass-card space-y-4 p-5 sm:p-8" aria-labelledby="member-emails-heading"><h2 className="font-serif text-2xl font-semibold" id="member-emails-heading">{labels.emails}</h2>{view.emails.length === 0 ? <p className="text-sm text-muted-foreground">{labels.empty}</p> : <ul className="space-y-3">{view.emails.map((email) => <li className="border-t border-border pt-3" key={email.id}><p>{email.subject}</p><p className="text-sm text-muted-foreground">{email.template} · {email.status} · {email.createdAt}</p></li>)}</ul>}</section>
    <section className="glass-card space-y-4 p-5 sm:p-8" aria-labelledby="member-events-heading"><h2 className="font-serif text-2xl font-semibold" id="member-events-heading">{labels.events}</h2>{view.events.length === 0 ? <p className="text-sm text-muted-foreground">{labels.empty}</p> : <ul className="space-y-3">{view.events.map((event) => <li className="border-t border-border pt-3" key={event.eventId}><p>{event.title}</p><p className="text-sm text-muted-foreground">{event.status} · {event.startsAt}</p></li>)}</ul>}</section>
    <section className="glass-card space-y-4 p-5 sm:p-8 lg:col-span-2" aria-labelledby="member-notes-heading"><h2 className="font-serif text-2xl font-semibold" id="member-notes-heading">{labels.notes}</h2>{view.notes.length === 0 ? <p className="text-sm text-muted-foreground">{labels.empty}</p> : <ul className="space-y-4">{view.notes.map((note) => <li className="border-t border-border pt-4" key={note.id}><p className="whitespace-pre-wrap">{note.body}</p><p className="mt-2 text-sm text-muted-foreground">{note.authorProfileId} · {note.createdAt}</p></li>)}</ul>}</section>
  </div>;
}