import {M2_LIVE_ENV_NAMES} from "../tests/fixtures/m2-runtime-env";
const journeyInputs=["M2_TEST_EXCO_EMAIL","M2_TEST_EXCO_PASSWORD","M2_TEST_SUPERADMIN_EMAIL","M2_TEST_SUPERADMIN_PASSWORD","HKWTIA_TEST_PENDING_MEMBERSHIP_ID","HKWTIA_TEST_GUEST_CHECKIN_EVENT_ID","HKWTIA_TEST_GUEST_CHECKIN_EMAIL","HKWTIA_TEST_GUEST_CHECKIN_EMAIL_ZH","HKWTIA_TEST_GUEST_RSVP_SLUG"] as const;
const missing=[...M2_LIVE_ENV_NAMES,...journeyInputs].filter(key=>!process.env[key]?.trim());
if(missing.length)throw new Error(`ISOLATED_ACCEPTANCE_MISSING: ${missing.join(', ')}`);
if(process.env.AUDIT_ISOLATED_ACCEPTANCE!=="true")throw new Error("ISOLATED_ACCEPTANCE_ATTESTATION_REQUIRED");
if(process.env.AUDIT_BATCH_WORKER_PAUSED!=="true")throw new Error("ISOLATED_BATCH_WORKER_PAUSED_ATTESTATION_REQUIRED");
if(process.env.MEMBER_IMPORT_ENABLED!=="true"||process.env.MEMBERSHIP_GRANTS_ENABLED!=="true")throw new Error("ISOLATED_IMPORT_AND_GRANT_CAPABILITIES_REQUIRED");
const app=new URL(process.env.PLAYWRIGHT_BASE_URL??process.env.APP_URL!);
if(app.hostname==='hkwtia.vercel.app'||(app.protocol!=='https:'&&!["localhost","127.0.0.1"].includes(app.hostname)))throw new Error("ISOLATED_PREVIEW_REQUIRED");
if(new URL(process.env.DATABASE_URL_TEST!).hostname!==process.env.M2_TEST_NEON_HOST)throw new Error("ISOLATED_DATABASE_HOST_MISMATCH");
if(!process.env.STRIPE_TEST_SECRET_KEY!.startsWith('sk_test_'))throw new Error("STRIPE_TEST_MODE_REQUIRED");
console.log("Isolated acceptance inputs present; host and test-mode guards passed. This does not prove provider activation.");
