import type {AppLocale} from "@/i18n/routing";
import type {AiOpsDashboardState} from "@/lib/aiops/dashboard";
import type {PublishedBuildLogSummary} from "@/lib/db/repos/public-posts";
import {ArchitectureDiagram} from "./architecture-diagram";
import {EvidenceLinks} from "./evidence-links";
import {MetricGrid} from "./metric-grid";
import {RenewalChart} from "./renewal-chart";
export type AiOpsDashboardLabels = Readonly<{currentMonth: string; partialMonth: string; lastUpdated: string; fresh: string; stale: string; empty: string; unavailable: string; notEnoughData: string; conversations: string; resolved: string; firstResponse: string; csat: string; escalation: string; failure: string; hoursSaved: string; llmCost: string; responses: string; samples: string; hours: string; resolutionTarget: string; csatTarget: string; renewalHeading: string; overallRenewal: string; firstYearRenewal: string; overallTarget: string; firstYearTarget: string; renewalChartTitle: string; renewalChartDescription: string; month: string; paid: string; due: string; rate: string; methodologyHeading: string; methodologyDescription: string; architectureHeading: string; architectureDescription: string; approvalGate: string; publicationGate: string; evidenceHeading: string; buildLogs: string; source: string; commits: string; deployment: string; acceptance: string; noBuildLogs: string}>;
type Evidence = Readonly<{id: "source" | "commits" | "deployment" | "acceptance"; href: string}>;
export function AiOpsDashboard({locale, state, buildLogs, evidence, labels}: Readonly<{locale: AppLocale; state: AiOpsDashboardState; buildLogs: readonly PublishedBuildLogSummary[]; evidence: readonly Evidence[]; labels: AiOpsDashboardLabels}>) { const detail = state.status === "unavailable" ? labels.unavailable : state.status === "empty" ? labels.empty : state.status === "fresh" ? labels.fresh : labels.stale; const current = state.current; return <main className="container mx-auto space-y-8 px-6 py-16"><header className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-widest text-primary">{labels.currentMonth}</p><p className="mt-2 text-muted-foreground">{detail}</p></header>{current ? <><MetricGrid metric={current} locale={locale} labels={labels} /><RenewalChart months={state.months} locale={locale} labels={labels} /></> : null}<section className="glass-card space-y-3 p-6"><h2 className="font-serif text-2xl font-semibold">{labels.methodologyHeading}</h2><p className="text-muted-foreground">{labels.methodologyDescription}</p></section><ArchitectureDiagram labels={labels} /><EvidenceLinks locale={locale} buildLogs={buildLogs} evidence={evidence} labels={labels} /></main>; }
