import type {AppLocale} from "@/i18n/routing";
import type {AiOpsDashboardState} from "@/lib/aiops/dashboard";
import type {PublishedBuildLogSummary} from "@/lib/db/repos/public-posts";
import {ArchitectureDiagram} from "./architecture-diagram";
import {EvidenceLinks} from "./evidence-links";
import {MetricGrid} from "./metric-grid";
import {RenewalChart} from "./renewal-chart";
// Decision 3: eyebrow/title/description move to the page-level PageHero
// (app/[locale]/(public)/ai-ops/page.tsx). This type keeps only what the metrics content
// itself needs.
export type AiOpsDashboardLabels = Readonly<{currentMonth:string;partialMonth:string;lastUpdated:string;fresh:string;stale:string;empty:string;unavailable:string;notEnoughData:string;conversations:string;resolved:string;firstResponse:string;csat:string;escalation:string;failure:string;hoursSaved:string;llmCost:string;responses:string;samples:string;hours:string;resolutionTarget:string;csatTarget:string;renewalHeading:string;overallRenewal:string;firstYearRenewal:string;overallTarget:string;firstYearTarget:string;renewalChartTitle:string;renewalChartDescription:string;month:string;paid:string;due:string;rate:string;methodologyHeading:string;methodologyDescription:string;architectureHeading:string;architectureDescription:string;approvalGate:string;publicationGate:string;evidenceHeading:string;buildLogs:string;source:string;commits:string;deployment:string;acceptance:string;noBuildLogs:string}>;
type Evidence=Readonly<{id:"source"|"commits"|"deployment"|"acceptance";href:string}>;
export function AiOpsDashboard({locale,state,buildLogs,evidence,labels}:Readonly<{locale:AppLocale;state:AiOpsDashboardState;buildLogs:readonly PublishedBuildLogSummary[];evidence:readonly Evidence[];labels:AiOpsDashboardLabels}>){const detail=state.status==="unavailable"?labels.unavailable:state.status==="empty"?labels.empty:state.status==="fresh"?labels.fresh:labels.stale;const current=state.current;const updated=current?new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Hong_Kong"}).format(current.refreshedAt):null;return <div className="container mx-auto space-y-8 px-6 py-16"><header className="flex flex-wrap gap-x-4 gap-y-2 text-sm text-muted-foreground"><span>{labels.currentMonth}</span>{current?.isPartialMonth?<span>{labels.partialMonth}</span>:null}{updated?<span>{labels.lastUpdated}: {updated}</span>:null}<span>{detail}</span></header>{current?<><MetricGrid metric={current} locale={locale} labels={labels}/><div className="flex flex-wrap gap-3 text-sm text-muted-foreground"><span>{labels.resolutionTarget}</span><span>{labels.csatTarget}</span></div><RenewalChart months={state.months} locale={locale} labels={labels}/></>:null}<section className="glass-card space-y-3 p-6"><h2 className="font-serif text-2xl font-semibold">{labels.methodologyHeading}</h2><p className="text-muted-foreground">{labels.methodologyDescription}</p></section><ArchitectureDiagram labels={labels}/><EvidenceLinks locale={locale} buildLogs={buildLogs} evidence={evidence} labels={labels}/></div>}
